# @summary Profile for managing a Cassandra node.
# This class wraps the cassandra_pfpt component module and provides its data via Hiera lookups.
class profile_cassandra_pfpt (
  # Core Settings
  String $cassandra_version                               = '4.1.10-1',
  String $java_version                                    = '11',
  String $cluster_name                                    = 'pfpt-cassandra-cluster',
  Array[String] $seeds                                     = [],
  String $cassandra_password                              = 'PP#C@ss@ndr@000',

  # Topology
  String $datacenter                                      = 'dc1',
  String $rack                                            = 'rack1',
  String $endpoint_snitch                                 = 'GossipingPropertyFileSnitch',
  Hash $racks                                             = {},

  # Networking
  String $listen_address                                  = $facts['networking']['ip'],
  Integer $native_transport_port                           = 9042,
  Integer $storage_port                                    = 7000,
  Integer $ssl_storage_port                                = 7001,
  Integer $rpc_port                                        = 9160,
  Boolean $start_native_transport                          = true,
  Boolean $start_rpc                                       = false, # Default to false for C* 4+

  # Directories & Paths
  String $data_dir                                        = '/var/lib/cassandra/data',
  String $commitlog_dir                                   = '/var/lib/cassandra/commitlog',
  String $saved_caches_dir                                = '/var/lib/cassandra/saved_caches',
  String $hints_directory                                 = '/var/lib/cassandra/hints',
  String $cdc_raw_directory                               = '/var/lib/cassandra/cdc_raw',

  # JVM & Performance
  String $max_heap_size                                   = '3G',
  String $gc_type                                         = 'G1GC',
  Integer $num_tokens                                      = 256,
  Optional[String] $initial_token                         = undef,
  Integer $concurrent_reads                                = 32,
  Integer $concurrent_writes                               = 32,
  Integer $concurrent_compactors                           = 4,
  Integer $compaction_throughput_mb_per_sec                = 16,
  Hash $jvm_additional_opts                               = {},

  # Security & Authentication
  String $authenticator                                   = 'PasswordAuthenticator',
  String $authorizer                                      = 'CassandraAuthorizer',
  String $role_manager                                    = 'CassandraRoleManager',
  Hash $cassandra_roles                                   = {},
  Hash $system_keyspaces_replication                      = {},

  # TLS/SSL Encryption
  Boolean $ssl_enabled                                     = false,
  String $keystore_password                                 = 'ChangeMe',
  String $truststore_password                               = 'changeit',
  String $internode_encryption                            = 'all',

  # System & OS Tuning
  Boolean $disable_swap                                    = true,
  Hash $sysctl_settings                                   = { 'fs.aio-max-nr' => 1048576 },
  Hash $limits_settings                                   = {
    'memlock' => 'unlimited',
    'nofile'  => 100000,
    'nproc'   => 32768,
    'as'      => 'unlimited',
  },

  # Package Management
  Boolean $manage_repo                                     = true,
  Array[String] $package_dependencies                      = ['cyrus-sasl-plain', 'jemalloc', 'python3', 'numactl', 'jq', 'awscli'],

  # Backup and Restore
  Boolean $incremental_backups                             = false,
  Boolean $manage_full_backups                             = false,
  Boolean $manage_incremental_backups                      = false,
  String $backup_backend                                  = 's3',
  String $backup_s3_bucket                                = 'puppet-cassandra-backups',
  Boolean $backup_upload_streaming                         = false,
  String $full_backup_schedule                            = 'daily',
  Variant[String, Array[String]] $incremental_backup_schedule = '0 */4 * * *',
  Integer $clearsnapshot_keep_days                         = 3,
  String $full_backup_log_file                            = '/var/log/cassandra/full_backup.log',
  String $incremental_backup_log_file                     = '/var/log/cassandra/incremental_backup.log',

  # Scheduled Repair
  Boolean $manage_scheduled_repair                         = false,
  String $repair_schedule                                 = '*-*-1/5 01:00:00',
  Optional[String] $repair_keyspace                       = undef,
  
  # Puppet Agent Management
  Optional[String] $puppet_cron_schedule                  = undef
) {

  class { 'cassandra_pfpt':
    cassandra_version              => $cassandra_version,
    java_version                   => $java_version,
    cluster_name                   => $cluster_name,
    seeds_list                     => $seeds,
    cassandra_password             => $cassandra_password,
    datacenter                     => $datacenter,
    rack                           => $rack,
    endpoint_snitch                => $endpoint_snitch,
    racks                          => $racks,
    listen_address                 => $listen_address,
    native_transport_port          => $native_transport_port,
    storage_port                   => $storage_port,
    ssl_storage_port               => $ssl_storage_port,
    rpc_port                       => $rpc_port,
    start_native_transport         => $start_native_transport,
    start_rpc                      => $start_rpc,
    data_dir                       => $data_dir,
    commitlog_dir                  => $commitlog_dir,
    saved_caches_dir               => $saved_caches_dir,
    hints_directory                => $hints_directory,
    cdc_raw_directory              => $cdc_raw_directory,
    max_heap_size                  => $max_heap_size,
    gc_type                        => $gc_type,
    num_tokens                     => $num_tokens,
    initial_token                  => $initial_token,
    concurrent_reads               => $concurrent_reads,
    concurrent_writes              => $concurrent_writes,
    concurrent_compactors          => $concurrent_compactors,
    compaction_throughput_mb_per_sec => $compaction_throughput_mb_per_sec,
    extra_jvm_args_override        => $jvm_additional_opts,
    authenticator                  => $authenticator,
    authorizer                     => $authorizer,
    role_manager                   => $role_manager,
    cassandra_roles                => $cassandra_roles,
    system_keyspaces_replication   => $system_keyspaces_replication,
    ssl_enabled                    => $ssl_enabled,
    keystore_password              => $keystore_password,
    truststore_password            => $truststore_password,
    internode_encryption           => $internode_encryption,
    disable_swap                   => $disable_swap,
    sysctl_settings                => $sysctl_settings,
    limits_settings                => $limits_settings,
    manage_repo                    => $manage_repo,
    package_dependencies           => $package_dependencies,
    incremental_backups            => $incremental_backups,
    manage_full_backups            => $manage_full_backups,
    manage_incremental_backups     => $manage_incremental_backups,
    backup_backend                 => $backup_backend,
    backup_s3_bucket               => $backup_s3_bucket,
    backup_upload_streaming        => $backup_upload_streaming,
    full_backup_schedule           => $full_backup_schedule,
    incremental_backup_schedule    => $incremental_backup_schedule,
    clearsnapshot_keep_days        => $clearsnapshot_keep_days,
    full_backup_log_file           => $full_backup_log_file,
    incremental_backup_log_file    => $incremental_backup_log_file,
    manage_scheduled_repair        => $manage_scheduled_repair,
    repair_schedule                => $repair_schedule,
    repair_keyspace                => $repair_keyspace,
    puppet_cron_schedule           => $puppet_cron_schedule,
    # These parameters from the component module do not have direct profile equivalents
    # and use their internal defaults or are managed internally.
    java_package_name            => undef,
    user                         => 'cassandra',
    group                        => 'cassandra',
    repo_baseurl                 => 'https://downloads.apache.org/cassandra/redhat/41x/',
    repo_gpgkey                  => 'https://downloads.apache.org/cassandra/KEYS',
    repo_gpgcheck                => true,
    repo_priority                => 1,
    repo_skip_if_unavailable     => false,
    repo_sslverify               => true,
    replace_address              => 'false',
    manage_bin_dir               => '/usr/local/bin',
    jamm_source                  => 'https://repo1.maven.org/maven2/com/github/jbellis/jamm/0.4.0/jamm-0.4.0.jar',
    jamm_target                  => '/usr/share/cassandra/lib/jamm-0.4.0.jar',
    enable_range_repair          => true,
    use_shenandoah_gc            => false,
    https_domain                 => 'cassandra.apache.org',
    target_dir                   => '/etc/cassandra/conf',
    keystore_path                => '/etc/cassandra/conf/keystore.jks',
    truststore_path              => '/etc/cassandra/conf/truststore.jks',
    internode_require_client_auth => true,
    client_optional              => false,
    client_require_client_auth   => true,
    client_keystore_path         => '/etc/cassandra/conf/client_keystore.jks',
    client_truststore_path       => '/etc/cassandra/conf/client_truststore.jks',
    client_truststore_password   => 'changeit',
    tls_protocol                 => 'TLSv1.2',
    tls_algorithm                => 'SunX509',
    store_type                   => 'JKS',
    tombstone_warn_threshold     => 1000,
    tombstone_failure_threshold  => 100000,
    change_password_cql          => '/usr/local/bin/change_password.cql',
    cqlsh_path_env               => '/usr/bin:/usr/local/bin',
    dynamic_snitch               => true,
    commit_failure_policy        => 'stop',
    commitlog_sync               => 'periodic',
    disk_failure_policy          => 'stop',
    max_hints_delivery_threads   => 2,
    native_transport_flush_in_batches_legacy => true,
    native_transport_max_frame_size_in_mb => 256,
    range_request_timeout_in_ms  => 10000,
    read_request_timeout_in_ms   => 5000,
    request_timeout_in_ms        => 10000,
    truncate_request_timeout_in_ms => 60000,
    write_request_timeout_in_ms  => 2000,
    commitlog_sync_period_in_ms  => 10000,
    rpc_keepalive                => true,
    thrift_framed_transport_size_in_mb => 15,
    enable_transient_replication => false,
    manage_jmx_security          => false,
    jmx_password_file_content    => '',
    jmx_access_file_content      => '',
    jmx_password_file_path       => '/etc/cassandra/jmxremote.password',
    jmx_access_file_path         => '/etc/cassandra/jmxremote.access',
    service_timeout_start_sec    => '900s',
    listen_interface             => undef,
    rpc_interface                => undef,
    broadcast_address            => undef,
    broadcast_rpc_address        => undef,
    counter_cache_size_in_mb     => undef,
    key_cache_size_in_mb         => undef,
    disk_optimization_strategy   => 'ssd',
    auto_snapshot                => true,
    phi_convict_threshold        => 8,
    concurrent_counter_writes    => 32,
    memtable_allocation_type     => 'heap_buffers',
    index_summary_capacity_in_mb => undef,
    file_cache_size_in_mb        => undef,
    manage_coralogix_agent       => false,
    coralogix_api_key            => '',
    coralogix_region             => 'us',
    coralogix_logs_enabled       => true,
    coralogix_metrics_enabled    => true,
    enable_materialized_views    => false,
    manage_jmx_exporter          => false,
    jmx_exporter_version         => '0.16.1',
    jmx_exporter_jar_source      => "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/${jmx_exporter_version}/jmx_prometheus_javaagent-${jmx_exporter_version}.jar",
    jmx_exporter_jar_target      => "/usr/share/cassandra/lib/jmx_prometheus_javaagent-${jmx_exporter_version}.jar",
    jmx_exporter_config_source   => 'puppet:///modules/cassandra_pfpt/jmx_exporter_config.yaml',
    jmx_exporter_config_target   => '/etc/cassandra/conf/jmx_exporter_config.yaml',
    jmx_exporter_port            => 7070,
    full_backup_script_path      => '/usr/local/bin/full-backup-to-s3.sh',
    incremental_backup_script_path => '/usr/local/bin/incremental-backup-to-s3.sh',
  }
}
