
export const puppetCode = {
  root: {
    'metadata.json': [
      '{',
      '  "name": "ggonda-cassandra",',
      '  "version": "1.0.0",',
      '  "author": "ggonda",',
      '  "summary": "Production-ready Puppet profile to manage Apache Cassandra at scale.",',
      '  "license": "Apache-2.0",',
      '  "source": "https://github.com/ggonda/profile_ggonda_cassandra",',
      '  "project_page": "https://github.com/ggonda/profile_ggonda_cassandra",',
      '  "issues_url": "https://github.com/ggonda/profile_ggonda_cassandra/issues",',
      '  "dependencies": [',
      '    {',
      '      "name": "puppetlabs/stdlib",',
      '      "version_requirement": ">= 6.0.0 < 9.0.0"',
      '    },',
      '    {',
      '      "name": "puppetlabs/apt",',
      '      "version_requirement": ">= 7.0.0 < 9.0.0"',
      '    },',
      '    {',
      '      "name": "puppetlabs/firewall",',
      '      "version_requirement": ">= 2.7.0 < 4.0.0"',
      '    }',
      '  ],',
      '  "operatingsystem_support": [',
      '    {',
      '      "operatingsystem": "RedHat",',
      '      "operatingsystemrelease": [ "7", "8", "9" ]',
      '    },',
      '    {',
      '      "operatingsystem": "CentOS",',
      '      "operatingsystemrelease": [ "7", "8", "9" ]',
      '    },',
      '    {',
      '      "operatingsystem": "Debian",',
      '      "operatingsystemrelease": [ "9", "10", "11" ]',
      '    },',
      '    {',
      '      "operatingsystem": "Ubuntu",',
      '      "operatingsystemrelease": [ "18.04", "20.04", "22.04" ]',
      '    }',
      '  ],',
      '  "requirements": [',
      '    {',
      '      "name": "puppet",',
      '      "version_requirement": ">= 6.0.0 < 8.0.0"',
      '    }',
      '  ]',
      '}',
    ].join('\n'),
  },
  manifests: {
    'init.pp': [
      '# @summary Manages installation and configuration of Apache Cassandra.',
      '# @param cassandra_version Version of Cassandra to install.',
      '# @param java_package Name of the Java package to install.',
      '# @param cluster_name Name of the Cassandra cluster.',
      '# @param seeds Comma-separated list of seed node IP addresses.',
      '# @param datacenter The datacenter name for this node.',
      '# @param rack The rack name for this node.',
      '# @param use_g1_gc Whether to use the G1GC garbage collector.',
      '# @param use_shenandoah_gc Whether to use the Shenandoah garbage collector.',
      '# @param racks A hash mapping datacenters to racks.',
      '# @param concurrent_compactors Number of concurrent compactors.',
      '# @param compaction_throughput_mb_per_sec Compaction throughput in MB/s.',
      '# @param tombstone_warn_threshold Tombstone warning threshold.',
      '# @param tombstone_failure_threshold Tombstone failure threshold.',
      '# @param sysctl_settings A hash of sysctl settings to apply.',
      '# @param limits_settings A hash of user limits to apply.',
      '# @param manage_repo Whether to manage the Cassandra repository.',
      '# @param manage_firewall Whether to manage firewall rules for Cassandra.',
      'class cassandra (',
      '  # Main class parameters, sourced from Hiera via lookup',
      '  String $cassandra_version        = lookup(\'cassandra::cassandra_version\', { default_value => \'4.1.10-1\' }),',
      '  String $java_version             = lookup(\'cassandra::java_version\', { default_value => \'11\' }),',
      '  String $cluster_name             = lookup(\'cassandra::cluster_name\', { default_value => \'ggonda-cass-cluster\' }),',
      '  String $seeds                    = lookup(\'cassandra::seeds\', { default_value => \'10.93.16.206,10.93.16.127,10.93.17.191\' }),',
      '  String $listen_address           = lookup(\'cassandra::listen_address\', { default_value => $facts[\'networking\'][\'ip\'] }),',
      '  Boolean $use_java11               = lookup(\'cassandra::use_java11\', { default_value => true }),',
      '  Optional[Boolean] $use_g1_gc     = lookup(\'cassandra::use_g1_gc\', { default_value => true }),',
      '  Optional[Boolean] $use_shenandoah_gc = lookup(\'cassandra::use_shenandoah_gc\', { default_value => false }),',
      '  Hash $racks                      = lookup(\'cassandra::racks\', { default_value => {} }),',
      '  String $datacenter               = lookup(\'cassandra::datacenter\', { default_value => \'dc1\' }),',
      '  String $rack                     = lookup(\'cassandra::rack\', { default_value => \'rack1\' }),',
      '  String $cassandra_password       = lookup(\'cassandra::cassandra_password\', { default_value => \'PP#C@ss@ndr@000\' }),',
      '  String $max_heap_size            = lookup(\'cassandra::max_heap_size\', { default_value => \'3G\' }),',
      '  String $gc_type                  = lookup(\'cassandra::gc_type\', { default_value => \'G1GC\' }),',
      '  String $data_dir                 = lookup(\'cassandra::data_dir\', { default_value => \'/var/lib/cassandra/data\' }),',
      '  String $commitlog_dir            = lookup(\'cassandra::commitlog_dir\', { default_value => \'/var/lib/cassandra/commitlog\' }),',
      '  String $hints_directory          = lookup(\'cassandra::hints_directory\', { default_value => \'/var/lib/cassandra/hints\' }),',
      '  Boolean $disable_swap             = lookup(\'cassandra::disable_swap\', { default_value => false }),',
      '  String $replace_address          = lookup(\'cassandra::replace_address\', { default_value => \'\' }),',
      '  Boolean $enable_range_repair      = lookup(\'cassandra::enable_range_repair\', { default_value => false }),',
      '  # SSL/TLS settings',
      '  Boolean $ssl_enabled              = lookup(\'cassandra::ssl_enabled\', { default_value => true }),',
      '  String $target_dir                  = lookup(\'cassandra::ssl_target_dir\', { default_value => \'/etc/pki/tls/certs\' }),',
      '  String $keystore_path            = lookup(\'cassandra::keystore_path\', { default_value => \'/etc/pki/tls/certs/etc/keystore.jks\' }),',
      '  String $keystore_password        = lookup(\'cassandra::keystore_password\', { default_value => \'ChangeMe\' }),',
      '  String $truststore_path          = lookup(\'cassandra::truststore_path\', { default_value => \'/etc/pki/ca-trust/extracted/java/cacerts\' }),',
      '  String $truststore_password      = lookup(\'cassandra::truststore_password\', { default_value => \'changeit\' }),',
      '  String $internode_encryption     = lookup(\'cassandra::internode_encryption\', { default_value => \'all\' }),',
      '  Boolean $internode_require_client_auth = lookup(\'cassandra::internode_require_client_auth\', { default_value => false }),',
      '  Boolean $client_optional             = lookup(\'cassandra::client_optional\', { default_value => false }),',
      '  Boolean $client_require_client_auth  = lookup(\'cassandra::client_require_client_auth\', { default_value => false }),',
      '  String  $client_keystore_path        = lookup(\'cassandra::client_keystore_path\', { default_value => \'/etc/pki/tls/certs/etc/keystore.jks\' }),',
      '  String  $client_truststore_path      = lookup(\'cassandra::client_truststore_path\', { default_value => \'/etc/pki/ca-trust/extracted/java/cacerts\' }),',
      '  String  $client_truststore_password  = lookup(\'cassandra::client_truststore_password\', { default_value => \'changeit\' }),',
      '  String $tls_protocol = lookup(\'cassandra::tls_protocol\', { default_value => \'TLS\' }),',
      '  String $tls_algorithm = lookup(\'cassandra::tls_algorithm\', { default_value => \'SunX509\' }),',
      '  String $store_type = lookup(\'cassandra::store_type\', { default_value => \'JKS\' }),',
      '  # cassandra.yaml main settings',
      '  Integer $concurrent_compactors          = lookup(\'cassandra::concurrent_compactors\', { default_value => 2 }),',
      '  Integer $compaction_throughput_mb_per_sec = lookup(\'cassandra::compaction_throughput_mb_per_sec\', { default_value => 16 }),',
      '  Integer $tombstone_warn_threshold       = lookup(\'cassandra::tombstone_warn_threshold\', { default_value => 1000 }),',
      '  Integer $tombstone_failure_threshold    = lookup(\'cassandra::tombstone_failure_threshold\', { default_value => 100000 }),',
      '  # OS Tuning settings',
      '  Hash $sysctl_settings                   = lookup(\'cassandra::sysctl_settings\', { default_value => { \'vm.max_map_count\' => \'1048576\' } }),',
      '  Hash $limits_settings                   = lookup(\'cassandra::limits_settings\', { default_value => { \'memlock\' => \'unlimited\', \'nofile\'  => \'100000\', \'nproc\'   => \'32768\', \'as\' => \'unlimited\' } }),',
      '  # New parameters for repo and firewall management',
      '  Boolean $manage_repo                    = lookup(\'cassandra::manage_repo\', { default_value => true }),',
      '  Boolean $manage_firewall                = lookup(\'cassandra::manage_firewall\', { default_value => true }),',
      '  String $cassandra_user = lookup(\'cassandra::user\', { default_value => \'cassandra\' }),',
      '  String $cassandra_group = lookup(\'cassandra::group\', { default_value => \'cassandra\' }),',
      '  # Internal settings',
      '  String $repo_baseurl               = lookup(\'cassandra::repo_baseurl\', { default_value => \'https://repocache.nonprod.ppops.net/artifactory/apache-org-cassandra/\' }),',
      '  String $repo_gpgkey                = lookup(\'cassandra::repo_gpgkey\', { default_value => \'https://repocache.nonprod.ppops.net/artifactory/apache-org-cassandra-gpg-keys/KEYS\' }),',
      '  Array[String] $package_dependencies = lookup(\'cassandra::package_dependencies\', { default_value => [\'jemalloc\',\'python3\',\'numactl\'] }),',
      '  String $manage_bin_dir             = lookup(\'cassandra::manage_bin_dir\', { default_value => \'/usr/local/bin\' }),',
      '  String $change_password_cql        = lookup(\'cassandra::change_password_cql\', { default_value => \'/tmp/change_password.cql\' }),',
      '  String $cqlsh_path_env             = lookup(\'cassandra::cqlsh_path_env\', { default_value => \'/usr/bin:/usr/local/bin\' }),',
      '  String $jamm_target                = lookup(\'cassandra::jamm_target\', { default_value => \'/usr/share/cassandra/lib/jamm-0.3.2.jar\' }),',
      '  String $jamm_source                = lookup(\'cassandra::jamm_source\', { default_value => \'puppet:///modules/ggonda-cassandra/jamm-0.3.2.jar\' })',
      ') {',
      '',
      '  # The main class now simply includes the component classes.',
      '  # This makes the module more modular and easier to understand.',
      '  contain cassandra::java',
      '  contain cassandra::install',
      '  contain cassandra::config',
      '  if $manage_firewall {',
      '    contain cassandra::firewall',
      '  }',
      '  contain cassandra::service',
      '',
      '  # Ensure classes are applied in the correct order.',
      '  Class[\'cassandra::java\'] ->',
      '  Class[\'cassandra::install\'] ->',
      '  Class[\'cassandra::config\'] ~>',
      '  Class[\'cassandra::service\']',
      '',
      '  if $manage_firewall {',
      '    Class[\'cassandra::config\'] -> Class[\'cassandra::firewall\']',
      '  }',
      '}',
    ].join('\n'),
    'params.pp': [
      '# @summary Default parameters for the Cassandra profile.',
      '# This class is now deprecated as all defaults are handled via lookup() in init.pp.',
      'class cassandra::params {',
      '  # All parameters have been moved to init.pp with lookup() for Hiera integration.',
      '}',
    ].join('\n'),
    'install.pp': [
      '# @summary Handles package installation for Cassandra and dependencies.',
      'class cassandra::install inherits cassandra {',
      '',
      '  # Ensure Cassandra user and group exist before anything else',
      '  user { $cassandra::cassandra_user:',
      '    ensure     => \'present\',',
      '    system     => true,',
      '  }',
      '',
      '  group { $cassandra::cassandra_group:',
      '    ensure => \'present\',',
      '    system => true,',
      '  }',
      '',
      '  # YUM Repo for Cassandra',
      '  if $cassandra::manage_repo {',
      '    if $facts[\'os\'][\'family\'] == \'RedHat\' {',
      '      $os_release_major = regsubst($facts[\'os\'][\'release\'][\'major\'], \'^(\\\\d+).*$\', \'\\\\1\')',
      '      yumrepo { \'cassandra\':',
      '        descr    => "Apache Cassandra ${cassandra::cassandra_version} for EL${os_release_major}",',
      '        baseurl  => $cassandra::repo_baseurl,',
      '        gpgcheck => 0,',
      '        enabled  => 1,',
      '        gpgkey   => $cassandra::repo_gpgkey,',
      '        repo_gpgcheck => 0,',
      '        skip_if_unavailable => 1,',
      '        priority => 99,',
      '        sslverify => 1,',
      '      }',
      '    } elsif $facts[\'os\'][\'family\'] == \'Debian\' {',
      '      include apt',
      '      apt::source { \'cassandra\':',
      '        location => $cassandra::repo_baseurl,',
      '        release  => $facts[\'os\'][\'distro\'][\'codename\'],',
      '        repos    => \'main\',',
      '        key      => {',
      '          id     => \'F758CE318D77295D\', # Example key, should be managed securely',
      '          source => $cassandra::repo_gpgkey,',
      '        },',
      '      }',
      '    }',
      '  }',
      '',
      '  # Install dependencies',
      '  package { $cassandra::package_dependencies:',
      '    ensure => \'present\',',
      '  }',
      '',
      '  # Install Cassandra and tools',
      '  package { \'cassandra\':',
      '    ensure  => $cassandra::cassandra_version,',
      '    require => Class[\'cassandra::java\'],',
      '  }',
      '',
      '  package { \'cassandra-tools\':',
      '    ensure  => $cassandra::cassandra_version,',
      '    require => Package[\'cassandra\'],',
      '  }',
      '}',
    ].join('\n'),
    'config.pp': [
      '# @summary Manages all configuration files for Cassandra.',
      'class cassandra::config inherits cassandra {',
      '',
      '  # Determine rack and DC dynamically for GCE',
      '  if $facts.get(\'gce\') {',
      '    $dc = $facts[\'gce\'][\'instance\'][\'zone\']',
      '    if $cassandra::racks.has_key($dc) {',
      '      $final_rack = $cassandra::racks[$dc]',
      '    } else {',
      '      $final_rack = \'rack1\' # Default if no specific rack is defined for the DC',
      '    }',
      '  } else {',
      '    $dc = $cassandra::datacenter',
      '    $final_rack = $cassandra::rack',
      '  }',
      '',
      '  # Create Cassandra data and commitlog directories',
      '  file { [$cassandra::data_dir, $cassandra::commitlog_dir, $cassandra::hints_directory]:',
      '    ensure  => \'directory\',',
      '    owner   => $cassandra::cassandra_user,',
      '    group   => $cassandra::cassandra_group,',
      '    mode    => \'0700\',',
      '    require => Class[\'cassandra::install\'], # Ensure user/group exist',
      '  }',
      '',
      '  # Create .cassandra directory for cqlshrc',
      '  file { \'/root/.cassandra\':',
      '    ensure => \'directory\',',
      '    owner  => \'root\',',
      '    group  => \'root\',',
      '    mode   => \'0700\',',
      '  }',
      '',
      '  file { $cassandra::jamm_target:',
      '    ensure  => \'file\',',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '    mode    => \'0644\',',
      '    source  => $cassandra::jamm_source,',
      '    require => Class[\'cassandra::install\'],',
      '  }',
      '',
      '  # Cassandra configuration files',
      '  file { \'/etc/cassandra/conf/cassandra.yaml\':',
      '    ensure  => \'file\',',
      '    content => template(\'ggonda-cassandra/cassandra.yaml.erb\'),',
      '    owner   => $cassandra::cassandra_user,',
      '    group   => $cassandra::cassandra_group,',
      '    mode    => \'0644\',',
      '    require => Class[\'cassandra::install\'],',
      '  }',
      '',
      '  file { \'/etc/cassandra/conf/cassandra-rackdc.properties\':',
      '    ensure  => \'file\',',
      '    content => template(\'ggonda-cassandra/cassandra-rackdc.properties.erb\'),',
      '    owner   => $cassandra::cassandra_user,',
      '    group   => $cassandra::cassandra_group,',
      '    mode    => \'0644\',',
      '    require => Class[\'cassandra::install\'],',
      '  }',
      '',
      '  file { \'/etc/cassandra/conf/jvm-server.options\':',
      '    ensure  => \'file\',',
      '    content => template(\'ggonda-cassandra/jvm-server.options.erb\'),',
      '    owner   => $cassandra::cassandra_user,',
      '    group   => $cassandra::cassandra_group,',
      '    mode    => \'0644\',',
      '    require => Class[\'cassandra::install\'],',
      '  }',
      '',
      '  file { \'/root/.cassandra/cqlshrc\':',
      '    ensure  => \'file\',',
      '    content => template(\'ggonda-cassandra/cqlshrc.erb\'),',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '    mode    => \'0600\',',
      '    require => File[\'/root/.cassandra\'],',
      '  }',
      '',
      '  # Deploy management scripts',
      '  file { $cassandra::manage_bin_dir:',
      '    ensure => \'directory\',',
      '    owner  => \'root\',',
      '    group  => \'root\',',
      '    mode   => \'0755\',',
      '  }',
      '',
      '  [ \'cassandra-upgrade-precheck.sh\', \'cluster-health.sh\', \'repair-node.sh\',',
      '    \'cleanup-node.sh\', \'take-snapshot.sh\', \'drain-node.sh\', \'rebuild-node.sh\',',
      '    \'garbage-collect.sh\', \'assassinate-node.sh\', \'upgrade-sstables.sh\',',
      '    \'backup-to-s3.sh\', \'prepare-replacement.sh\', \'version-check.sh\',',
      '    \'cassandra_range_repair.py\', \'range-repair.sh\', \'robust_backup.sh\',',
      '    \'restore_from_backup.sh\', \'node_health_check.sh\', \'rolling_restart.sh\' ].each |$script| {',
      '    file { "${cassandra::manage_bin_dir}/${script}":',
      '      ensure  => \'file\',',
      '      source  => "puppet:///modules/ggonda-cassandra/scripts/${script}",',
      '      owner   => \'root\',',
      '      group   => \'root\',',
      '      mode    => \'0755\',',
      '    }',
      '  }',
      '',
      '  # OS Tuning for Cassandra',
      '  if $cassandra::disable_swap {',
      '    exec { \'swapoff -a\':',
      '      command  => \'/sbin/swapoff -a\',',
      '      unless   => \'/sbin/swapon -s | /bin/grep -qE "^/[^ ]+\\\\s+partition\\\\s+0\\\\s+0$"\',',
      '      path     => [\'/usr/bin\', \'/usr/sbin\', \'/bin\', \'/sbin\'],',
      '      before   => File[\'/etc/sysctl.d/99-cassandra.conf\'],',
      '    }',
      '    $merged_sysctl = $cassandra::sysctl_settings + { \'vm.swappiness\' => 0 }',
      '  } else {',
      '    $merged_sysctl = $cassandra::sysctl_settings',
      '  }',
      '',
      '  file { \'/etc/sysctl.d/99-cassandra.conf\':',
      '    ensure  => \'file\',',
      '    content => epp(\'ggonda-cassandra/sysctl.conf.epp\', { \'settings\' => $merged_sysctl }),',
      '    mode    => \'0644\',',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '    notify  => Exec[\'apply_sysctl_cassandra\'],',
      '  }',
      '',
      '  exec { \'apply_sysctl_cassandra\':',
      '    command     => \'/sbin/sysctl -p /etc/sysctl.d/99-cassandra.conf\',',
      '    path        => [\'/usr/bin\', \'/usr/sbin\', \'/bin\', \'/sbin\'],',
      '    refreshonly => true,',
      '  }',
      '',
      '  file { \'/etc/security/limits.d/cassandra.conf\':',
      '    ensure  => \'file\',',
      '    content => template(\'ggonda-cassandra/cassandra_limits.conf.erb\'),',
      '    mode    => \'0644\',',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '  }',
      '}',
    ].join('\n'),
    'service.pp': [
      '# @summary Manages the Cassandra service, including password changes and range repair.',
      'class cassandra::service inherits cassandra {',
      '',
      '  # Cassandra service',
      '  service { \'cassandra\':',
      '    ensure     => running,',
      '    enable     => true,',
      '    hasstatus  => true,',
      '    hasrestart => true,',
      '  }',
      '',
      '  file { $cassandra::change_password_cql:',
      '    ensure  => file,',
      '    content => "ALTER USER cassandra WITH PASSWORD \'${cassandra::cassandra_password}\';\\\\n",',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '    mode    => \'0600\',',
      '  }',
      '',
      '  # Wait for Cassandra to start up before attempting to change password',
      '  exec { \'change_cassandra_password\':',
      '    command     => "cqlsh -u cassandra -p cassandra -f ${cassandra::change_password_cql}",',
      '    path        => $cassandra::cqlsh_path_env,',
      '    tries       => 12, # Try 12 times',
      '    try_sleep   => 10, # Wait 10 seconds between tries (total 2 minutes)',
      '    unless      => "cqlsh -u cassandra -p \'${cassandra::cassandra_password}\' -e \'SELECT cluster_name FROM system.local;\' ${cassandra::listen_address} >/dev/null 2>&1",',
      '    require     => Service[\'cassandra\'],',
      '  }',
      '',
      '  # Range Repair Service (Systemd)',
      '  $range_repair_ensure = $cassandra::enable_range_repair ? { true => \'running\', default => \'stopped\' }',
      '  $range_repair_enable = $cassandra::enable_range_repair ? { true => true, default => false }',
      '',
      '  file { \'/etc/systemd/system/range-repair.service\':',
      '    ensure  => \'file\',',
      '    content => template(\'ggonda-cassandra/range-repair.service.erb\'),',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '    mode    => \'0644\',',
      '    notify  => Exec[\'systemctl_daemon_reload_range_repair\'],',
      '  }',
      '',
      '  exec { \'systemctl_daemon_reload_range_repair\':',
      '    command     => \'/bin/systemctl daemon-reload\',',
      '    path        => [\'/usr/bin\', \'/bin\'],',
      '    refreshonly => true,',
      '    before      => Service[\'range-repair\'],',
      '  }',
      '',
      '  service { \'range-repair\':',
      '    ensure    => $range_repair_ensure,',
      '    enable    => $range_repair_enable,',
      '    hasstatus => true,',
      '    hasrestart => true,',
      '    subscribe => File[\'/etc/systemd/system/range-repair.service\'],',
      '  }',
      '}',
    ].join('\n'),
    'java.pp': [
      '# @summary Manages Java installation for Cassandra.',
      'class cassandra::java inherits cassandra {',
      '',
      '  # Determine the correct Java package name based on the version and OS family',
      '  if $cassandra::use_java11 {',
      '    $default_java_package = $facts[\'os\'][\'family\'] ? {',
      '      \'RedHat\' => \'java-11-openjdk-headless\',',
      '      \'Debian\' => \'openjdk-11-jre-headless\',',
      '      default  => fail("Unsupported OS family for Java 11 installation: ${facts[\'os\'][\'family\']}"),',
      '    }',
      '  } else {',
      '    $default_java_package = $facts[\'os\'][\'family\'] ? {',
      '      \'RedHat\' => \'java-1.8.0-openjdk-headless\',',
      '      \'Debian\' => \'openjdk-8-jre-headless\',',
      '      default  => fail("Unsupported OS family for Java 8 installation: ${facts[\'os\'][\'family\']}"),',
      '    }',
      '  }',
      '',
      '  # Use the Hiera-provided package name if it exists, otherwise use the default',
      '  $java_package_name = lookup(\'cassandra::java_package_name\', { default_value => $default_java_package })',
      '',
      '  package { $java_package_name:',
      '    ensure  => present,',
      '  }',
      '}',
    ].join('\n'),
    'firewall.pp': [
      '# @summary Manages firewall rules for Cassandra.',
      'class cassandra::firewall {',
      '',
      '  # Default Cassandra ports',
      '  $cassandra_ports = {',
      '    \'7000\' => \'Cassandra Internode\',',
      '    \'7001\' => \'Cassandra Internode SSL\',',
      '    \'7199\' => \'Cassandra JMX\',',
      '    \'9042\' => \'Cassandra CQL\',',
      '    \'9160\' => \'Cassandra Thrift\',',
      '  }',
      '',
      '  $cassandra_ports.each |$port, $comment| {',
      '    firewall { "100 allow ${comment} access":',
      '      dport  => $port,',
      '      proto  => \'tcp\',',
      '      action => \'accept\',',
      '    }',
      '  }',
      '}',
    ].join('\n'),
  },
  templates: {
    'cassandra.yaml.erb': [
      '# cassandra.yaml',
      '# Generated by Puppet from ggonda-cassandra/cassandra.yaml.erb. DO NOT EDIT.',
      '',
      'cluster_name: \'<%= @cassandra_version.to_s.start_with?("3.") ? @cluster_name : @cassandra.cluster_name %>\'',
      'num_tokens: 256',
      'partitioner: org.apache.cassandra.dht.Murmur3Partitioner',
      '',
      'data_file_directories:',
      '    - \'<%= @data_dir %>\'',
      'commitlog_directory: \'<%= @commitlog_dir %>\'',
      'saved_caches_directory: /var/lib/cassandra/saved_caches',
      'hints_directory: \'<%= @hints_directory %>\'',
      '',
      'seed_provider:',
      '    - class_name: org.apache.cassandra.locator.SimpleSeedProvider',
      '      parameters:',
      '          - seeds: "<%= @seeds %>"',
      '',
      'listen_address: \'<%= @listen_address %>\'',
      'rpc_address: \'<%= @listen_address %>\'',
      'native_transport_port: 9042',
      'endpoint_snitch: GossipingPropertyFileSnitch',
      'dynamic_snitch: true',
      'authenticator: PasswordAuthenticator',
      'authorizer: CassandraAuthorizer',
      'start_native_transport: true',
      'role_manager: CassandraRoleManager',
      'cdc_raw_directory: /var/lib/cassandra/cdc_raw',
      'commit_failure_policy: stop',
      'commitlog_sync: periodic',
      'disk_failure_policy: stop',
      'incremental_backups: false',
      'max_hints_delivery_threads: 2',
      'native_transport_flush_in_batches_legacy: false',
      'native_transport_max_frame_size_in_mb: 128',
      'range_request_timeout_in_ms: 10000',
      'read_request_timeout_in_ms: 5000',
      'request_timeout_in_ms: 10000',
      'ssl_storage_port: 7001',
      'storage_port: 7000',
      'truncate_request_timeout_in_ms: 60000',
      'write_request_timeout_in_ms: 10000',
      'commitlog_sync_period_in_ms: 10000',
      '',
      '<% if @cassandra_version.to_s.start_with?(\'3.\') -%>',
      'start_rpc: true',
      'rpc_port: 9160',
      'rpc_keepalive: true',
      'thrift_framed_transport_size_in_mb: 15',
      '<% else -%>',
      '# Cassandra 4.x / 5.x specific settings',
      'enable_transient_replication: false',
      '<% end -%>',
      '',
      '<% if @ssl_enabled -%>',
      '# --- Internode (node-to-node) encryption ---',
      'server_encryption_options:',
      '  internode_encryption: <%= @internode_encryption || \'all\' %>  # \'none\' | \'dc\' | \'rack\' | \'all\'',
      '  keystore: <%= @keystore_path || "#{@target_dir}/etc/keystore.jks" %>',
      '  keystore_password: <%= @keystore_password %>',
      '  # Set to true only if you want nodes to present client certs (mutual TLS for internode)',
      '  require_client_auth: <%= @internode_require_client_auth ? \'true\' : \'false\' %>',
      '  <% if @truststore_path && @truststore_password -%>',
      '  truststore: <%= @truststore_path %>',
      '  truststore_password: <%= @truststore_password %>',
      '  <% end -%>',
      '  <% if @tls_protocol -%>',
      '  protocol: <%= @tls_protocol %>            # e.g., TLS',
      '  <% end -%>',
      '  <% if @tls_algorithm -%>',
      '  algorithm: <%= @tls_algorithm %>          # e.g., SunX509',
      '  <% end -%>',
      '  <% if @store_type -%>',
      '  store_type: <%= @store_type %>            # e.g., JKS',
      '  <% end -%>',
      '',
      '# --- Client (app-to-node) encryption ---',
      'client_encryption_options:',
      '  enabled: true',
      '  optional: <%= @client_optional ? \'true\' : \'false\' %>',
      '  keystore: <%= @client_keystore_path || "#{@target_dir}/etc/keystore.jks" %>',
      '  keystore_password: <%= @keystore_password %>',
      '<% end -%>',
    ].join('\n'),
    'cassandra-rackdc.properties.erb': [
      '# cassandra-rackdc.properties',
      '# Generated by Puppet from ggonda-cassandra/cassandra-rackdc.properties.erb',
      '# Used by GossipingPropertyFileSnitch to determine rack and datacenter for this node.',
      'dc=<%= @dc %>',
      'rack=<%= @final_rack %>',
    ].join('\n'),
    'jvm-server.options.erb': [
      '# JVM configuration for Cassandra',
      '-ea',
      '',
      '-da:net.openhft...',
      '',
      '# Heap size',
      '-Xms<%= @max_heap_size %>',
      '-Xmx<%= @max_heap_size %>',
      '',
      '# GC type',
      '<% if @gc_type == \'G1GC\' %>',
      '-XX:+UseG1GC',
      '<% if @java_version.to_i < 14 %>',
      '-XX:G1HeapRegionSize=16M',
      '-XX:MaxGCPauseMillis=500',
      '-XX:InitiatingHeapOccupancyPercent=75',
      '-XX:+ParallelRefProcEnabled',
      '-XX:+AggressiveOpts',
      '<% end %>',
      '<% elsif @gc_type == \'CMS\' && @java_version.to_i < 14 %>',
      '-XX:+UseConcMarkSweepGC',
      '-XX:+CMSParallelRemarkEnabled',
      '-XX:SurvivorRatio=8',
      '-XX:MaxTenuringThreshold=1',
      '-XX:CMSInitiatingOccupancyFraction=75',
      '-XX:+UseCMSInitiatingOccupancyOnly',
      '-XX:+CMSClassUnloadingEnabled',
      '-XX:+AlwaysPreTouch',
      '<% end %>',
      '',
      '# GC logging',
      '<% if @java_version.to_i >= 11 %>',
      '-Xlog:gc*:/var/log/cassandra/gc.log:time,uptime,pid,tid,level,tags:filecount=10,filesize=100M',
      '<% else %>',
      '-Xloggc:/var/log/cassandra/gc.log',
      '-XX:+PrintGCDetails',
      '-XX:+PrintGCDateStamps',
      '-XX:+PrintHeapAtGC',
      '-XX:+PrintTenuringDistribution',
      '-XX:+PrintGCApplicationStoppedTime',
      '-XX:+UseGCLogFileRotation',
      '-XX:NumberOfGCLogFiles=10',
      '-XX:GCLogFileSize=100M',
      '<% end %>',
      '',
      '# Other common options',
      '-Dcassandra.jmx.local.port=7199',
      '-Djava.net.preferIPv4Stack=true',
      '-Dcom.sun.management.jmxremote.port=7199',
      '-Dcom.sun.management.jmxremote.rmi.port=7199',
      '-Dcom.sun.management.jmxremote.ssl=false',
      '-Dcom.sun.management.jmxremote.authenticate=false',
      '-Dlogback.configurationFile=logback.xml',
      '-Dlogback.defaultConfigurationFile=logback-default.xml',
      '',
      '<% if !@replace_address.empty? %>',
      '# Replace dead node at first boot (set by Hiera/Puppet)',
      '-Dcassandra.replace_address_first_boot=<%= @replace_address %>',
      '<% end %>',
    ].join('\n'),
    'cqlshrc.erb': [
      '# cqlshrc configuration file generated by Puppet',
      '',
      '[authentication]',
      'username = cassandra',
      'password = <%= @cassandra_password %>',
      '',
      '[connection]',
      'hostname = <%= @listen_address %>',
      'port = 9042',
      '',
      '<% if @ssl_enabled %>',
      '[ssl]',
      'certfile =  <%= "#{@target_dir}/etc/keystore.pem" %>',
      'version = SSLv23',
      'validate = false',
      '<% end %>',
    ].join('\n'),
    'range-repair.service.erb': [
      '[Unit]',
      'Description=Cassandra Range Repair Service',
      '',
      '[Service]',
      'Type=simple',
      'User=cassandra',
      'Group=cassandra',
      'ExecStart=/usr/local/bin/range-repair.sh',
      'Restart=on-failure',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
    ].join('\n'),
    'cassandra_limits.conf.erb': [
      '# Generated by Puppet',
      '# /etc/security/limits.d/cassandra.conf',
      '',
      '<% @cassandra.limits_settings.each do |limit, value| -%>',
      '<%= @cassandra.cassandra_user %> - <%= limit %> <%= value %>',
      '<% end -%>',
    ].join('\n'),
    'sysctl.conf.epp': [
      '# Generated by Puppet',
      '# /etc/sysctl.d/99-cassandra.conf',
      '<% $settings.each |$key, $value| -%>',
      '<%= $key %> = <%= $value %>',
      '<% end -%>',
    ].join('\n'),
  },
  scripts: {
    'cassandra-upgrade-precheck.sh': '#!/bin/bash\n# Placeholder for cassandra-upgrade-precheck.sh\necho "Cassandra Upgrade Pre-check Script"',
    'cluster-health.sh': [
      '#!/bin/bash',
      '# cluster-health.sh: Provides a status overview of the Cassandra cluster.',
      '# Uses nodetool to check the state of all nodes.',
      '',
      'set -e',
      '',
      'echo "--- Cassandra Cluster Status ---"',
      'nodetool status',
      'echo "------------------------------"',
      'exit 0',
    ].join('\n'),
    'repair-node.sh': [
      '#!/bin/bash',
      '# repair-node.sh: Performs a primary-range repair on the local node.',
      '# This is a critical maintenance task for data consistency.',
      '',
      'set -e',
      '',
      'echo "--- Starting Node Repair (Primary Range) ---"',
      'nodetool repair -pr',
      'echo "--- Node Repair Finished ---"',
      'exit 0',
    ].join('\n'),
    'cleanup-node.sh': '#!/bin/bash\n# Placeholder for cleanup-node.sh\necho "Cleanup Node Script"',
    'take-snapshot.sh': '#!/bin/bash\n# Placeholder for take-snapshot.sh\necho "Take Snapshot Script"',
    'drain-node.sh': [
      '#!/bin/bash',
      '# drain-node.sh: Safely drains the node before shutdown or maintenance.',
      '# This flushes all memtables and stops listening for connections.',
      '',
      'set -e',
      '',
      'echo "--- Draining Cassandra Node ---"',
      'nodetool drain',
      'echo "--- Node Successfully Drained ---"',
      'exit 0',
    ].join('\n'),
    'rebuild-node.sh': '#!/bin/bash\n# Placeholder for rebuild-node.sh\necho "Rebuild Node Script"',
    'garbage-collect.sh': '#!/bin/bash\n# Placeholder for garbage-collect.sh\necho "Garbage Collect Script"',
    'assassinate-node.sh': '#!/bin/bash\n# Placeholder for assassinate-node.sh\necho "Assassinate Node Script"',
    'upgrade-sstables.sh': '#!/bin/bash\n# Placeholder for upgrade-sstables.sh\necho "Upgrade SSTables Script"',
    'backup-to-s3.sh': '#!/bin/bash\n# Placeholder for backup-to-s3.sh\necho "Backup to S3 Script"',
    'prepare-replacement.sh': '#!/bin/bash\n# Placeholder for prepare-replacement.sh\necho "Prepare Replacement Script"',
    'version-check.sh': '#!/bin/bash\n# Placeholder for version-check.sh\necho "Version Check Script"',
    'cassandra_range_repair.py': '#!/usr/bin/env python3\n# Placeholder for cassandra_range_repair.py\nprint("Cassandra Range Repair Python Script")',
    'range-repair.sh': '#!/bin/bash\n# Placeholder for range-repair.sh\necho "Range Repair Script"',
    'robust_backup.sh': '#!/bin/bash\necho "Robust Backup Script Placeholder"',
    'restore_from_backup.sh': '#!/bin/bash\necho "Restore from Backup Script Placeholder"',
    'node_health_check.sh': '#!/bin/bash\necho "Node Health Check Script Placeholder"',
    'rolling_restart.sh': '#!/bin/bash\necho "Rolling Restart Script Placeholder"',
  },
  files: {
    'jamm-0.3.2.jar': '', // Placeholder for binary file
  },
};
