
export const puppetCode = {
  root: {
    'metadata.json': [
      '{',
      '  "name": "ggonda-cassandra",',
      '  "version": "1.0.0",',
      '  "author": "ggonda",',
      '  "summary": "Production-ready Puppet profile to manage Apache Cassandra at scale.",',
      '  "license": "Apache-2.0",',
      '  "source": "https://github.com/ggonda/profile_ggonda_cassandra",',
      '  "project_page": "https://github.com/ggonda/profile_ggonda_cassandra",',
      '  "issues_url": "https://github.com/ggonda/profile_ggonda_cassandra/issues",',
      '  "dependencies": [',
      '  ],',
      '  "operatingsystem_support": [',
      '    {',
      '      "operatingsystem": "RedHat",',
      '      "operatingsystemrelease": [ "7", "8", "9" ]',
      '    },',
      '    {',
      '      "operatingsystem": "CentOS",',
      '      "operatingsystemrelease": [ "7", "8", "9" ]',
      '    },',
      '    {',
      '      "operatingsystem": "Debian",',
      '      "operatingsystemrelease": [ "9", "10", "11" ]',
      '    },',
      '    {',
      '      "operatingsystem": "Ubuntu",',
      '      "operatingsystemrelease": [ "18.04", "20.04", "22.04" ]',
      '    }',
      '  ],',
      '  "requirements": [',
      '    {',
      '      "name": "puppet",',
      '      "version_requirement": ">= 6.0.0 < 8.0.0"',
      '    }',
      '  ]',
      '}',
    ].join('\n'),
  },
  manifests: {
    'init.pp': [
      '# @summary Manages installation and configuration of Apache Cassandra.',
      '# This profile class fetches all configuration from Hiera and passes it to the config class.',
      'class cassandra (',
      '  String $cassandra_version,',
      '  String $java_version,',
      '  Optional[String] $java_package_version,',
      '  String $cluster_name,',
      '  String $seeds,',
      '  String $listen_address,',
      '  Boolean $use_java11,',
      '  Optional[Boolean] $use_g1_gc,',
      '  Optional[Boolean] $use_shenandoah_gc,',
      '  Hash $racks,',
      '  String $datacenter,',
      '  String $rack,',
      '  String $cassandra_password,',
      '  String $max_heap_size,',
      '  String $gc_type,',
      '  String $data_dir,',
      '  String $commitlog_dir,',
      '  String $hints_directory,',
      '  Boolean $disable_swap,',
      '  String $replace_address,',
      '  Boolean $enable_range_repair,',
      '  Boolean $ssl_enabled,',
      '  String $target_dir,',
      '  String $keystore_path,',
      '  String $keystore_password,',
      '  String $truststore_path,',
      '  String $truststore_password,',
      '  String $internode_encryption,',
      '  Boolean $internode_require_client_auth,',
      '  Boolean $client_optional,',
      '  Boolean $client_require_client_auth,',
      '  String $client_keystore_path,',
      '  String $client_truststore_path,',
      '  String $client_truststore_password,',
      '  String $tls_protocol,',
      '  String $tls_algorithm,',
      '  String $store_type,',
      '  Integer $concurrent_compactors,',
      '  Integer $compaction_throughput_mb_per_sec,',
      '  Integer $tombstone_warn_threshold,',
      '  Integer $tombstone_failure_threshold,',
      '  Hash $sysctl_settings,',
      '  Hash $limits_settings,',
      '  Boolean $manage_repo,',
      '  String $user,',
      '  String $group,',
      '  String $repo_baseurl,',
      '  String $repo_gpgkey,',
      '  Array[String] $package_dependencies,',
      '  String $manage_bin_dir,',
      '  String $change_password_cql,',
      '  String $cqlsh_path_env,',
      '  String $jamm_target,',
      '  String $jamm_source',
      ') {',
      '  # This class contains the main logic and includes the other component classes.',
      '  contain cassandra::java',
      '  contain cassandra::install',
      '  contain cassandra::core_config',
      '  contain cassandra::service',
      '',
      '  # Ensure classes are applied in the correct order.',
      '  Class[\'cassandra::java\'] ->',
      '  Class[\'cassandra::install\'] ->',
      '  Class[\'cassandra::core_config\'] ~>',
      '  Class[\'cassandra::service\']',
      '}',
    ].join('\n'),
    'params.pp': null,
    'install.pp': [
      '# @summary Handles package installation for Cassandra and dependencies.',
      'class cassandra::install inherits cassandra {',
      '',
      '  # Ensure Cassandra user and group exist before anything else',
      '  user { $cassandra::user:',
      '    ensure     => \'present\',',
      '    system     => true,',
      '  }',
      '',
      '  group { $cassandra::group:',
      '    ensure => \'present\',',
      '    system => true,',
      '  }',
      '',
      '  # YUM Repo for Cassandra',
      '  if $cassandra::manage_repo {',
      '    if $facts[\'os\'][\'family\'] == \'RedHat\' {',
      '      $os_release_major = regsubst($facts[\'os\'][\'release\'][\'major\'], \'^(\\\\d+).*$\', \'\\\\1\')',
      '      yumrepo { \'cassandra\':',
      '        descr    => "Apache Cassandra ${cassandra::cassandra_version} for EL${os_release_major}",',
      '        baseurl  => $cassandra::repo_baseurl,',
      '        gpgcheck => 1,',
      '        enabled  => 1,',
      '        gpgkey   => $cassandra::repo_gpgkey,',
      '        repo_gpgcheck => 0,',
      '        skip_if_unavailable => 1,',
      '        priority => 99,',
      '        sslverify => 1,',
      '      }',
      '    }',
      '  }',
      '',
      '  # Install dependencies',
      '  package { $cassandra::package_dependencies:',
      '    ensure => \'present\',',
      '  }',
      '',
      '  # Install Cassandra and tools',
      '  package { \'cassandra\':',
      '    ensure  => $cassandra::cassandra_version,',
      '    require => Class[\'cassandra::java\'],',
      '  }',
      '',
      '  package { \'cassandra-tools\':',
      '    ensure  => $cassandra::cassandra_version,',
      '    require => Package[\'cassandra\'],',
      '  }',
      '}',
    ].join('\n'),
    'config.pp': [
      '# @summary Manages all configuration files for Cassandra.',
      'class cassandra::core_config inherits cassandra {',
      '',
      '  # Create Cassandra data and commitlog directories',
      '  file { [$cassandra::data_dir, $cassandra::commitlog_dir, $cassandra::hints_directory]:',
      '    ensure  => \'directory\',',
      '    owner   => $cassandra::user,',
      '    group   => $cassandra::group,',
      '    mode    => \'0700\',',
      '    require => Class[\'cassandra::install\'], # Ensure user/group exist',
      '  }',
      '',
      '  # Create .cassandra directory for cqlshrc',
      '  file { \'/root/.cassandra\':',
      '    ensure => \'directory\',',
      '    owner  => \'root\',',
      '    group  => \'root\',',
      '    mode   => \'0700\',',
      '  }',
      '',
      '  file { $cassandra::jamm_target:',
      '    ensure  => \'file\',',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '    mode    => \'0644\',',
      '    source  => $cassandra::jamm_source,',
      '    require => Class[\'cassandra::install\'],',
      '  }',
      '',
      '  # Cassandra configuration files',
      '  file { \'/etc/cassandra/conf/cassandra.yaml\':',
      '    ensure  => \'file\',',
      '    content => template(\'cassandra/cassandra.yaml.erb\'),',
      '    owner   => $cassandra::user,',
      '    group   => $cassandra::group,',
      '    mode    => \'0644\',',
      '    require => Class[\'cassandra::install\'],',
      '  }',
      '',
      '  file { \'/etc/cassandra/conf/cassandra-rackdc.properties\':',
      '    ensure  => \'file\',',
      '    content => template(\'cassandra/cassandra-rackdc.properties.erb\'),',
      '    owner   => $cassandra::user,',
      '    group   => $cassandra::group,',
      '    mode    => \'0644\',',
      '    require => Class[\'cassandra::install\'],',
      '  }',
      '',
      '  file { \'/etc/cassandra/conf/jvm-server.options\':',
      '    ensure  => \'file\',',
      '    content => template(\'cassandra/jvm-server.options.erb\'),',
      '    owner   => $cassandra::user,',
      '    group   => $cassandra::group,',
      '    mode    => \'0644\',',
      '    require => Class[\'cassandra::install\'],',
      '  }',
      '',
      '  file { \'/root/.cassandra/cqlshrc\':',
      '    ensure  => \'file\',',
      '    content => template(\'cassandra/cqlshrc.erb\'),',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '    mode    => \'0600\',',
      '    require => File[\'/root/.cassandra\'],',
      '  }',
      '',
      '  # Deploy management scripts',
      '  file { $cassandra::manage_bin_dir:',
      '    ensure => \'directory\',',
      '    owner  => \'root\',',
      '    group  => \'root\',',
      '    mode   => \'0755\',',
      '  }',
      '',
      '  [ \'cassandra-upgrade-precheck.sh\', \'cluster-health.sh\', \'repair-node.sh\',',
      '    \'cleanup-node.sh\', \'take-snapshot.sh\', \'drain-node.sh\', \'rebuild-node.sh\',',
      '    \'garbage-collect.sh\', \'assassinate-node.sh\', \'upgrade-sstables.sh\',',
      '    \'backup-to-s3.sh\', \'prepare-replacement.sh\', \'version-check.sh\',',
      '    \'cassandra_range_repair.py\', \'range-repair.sh\', \'robust_backup.sh\',',
      '    \'restore_from_backup.sh\', \'node_health_check.sh\', \'rolling_restart.sh\' ].each |$script| {',
      '    file { "${cassandra::manage_bin_dir}/${script}":',
      '      ensure  => \'file\',',
      '      source  => "puppet:///modules/cassandra/scripts/${script}",',
      '      owner   => \'root\',',
      '      group   => \'root\',',
      '      mode    => \'0755\',',
      '    }',
      '  }',
      '',
      '  # OS Tuning for Cassandra',
      '  if $cassandra::disable_swap {',
      '    # Disable currently running swap',
      '    exec { \'swapoff -a\':',
      '      command  => \'/sbin/swapoff -a\',',
      '      unless   => \'/bin/cat /proc/swaps | /bin/grep -q "^/dev" -v\',',
      '      path     => [\'/usr/bin\', \'/usr/sbin\', \'/bin\', \'/sbin\'],',
      '    }',
      '    # Permanently disable swap in fstab',
      '    augeas { \'fstab_no_swap\':',
      '      context => \'/files/etc/fstab\',',
      '      changes => \'set */[spec="swap"]/#comment "swap"\',',
      '      onlyif  => \'get */[spec="swap"] != ""\',',
      '      require => Exec[\'swapoff -a\'],',
      '    }',
      '    $merged_sysctl = $cassandra::sysctl_settings + { \'vm.swappiness\' => 0 }',
      '  } else {',
      '    $merged_sysctl = $cassandra::sysctl_settings',
      '  }',
      '',
      '  file { \'/etc/sysctl.d/99-cassandra.conf\':',
      '    ensure  => \'file\',',
      '    content => epp(\'cassandra/sysctl.conf.epp\', { \'settings\' => $merged_sysctl }),',
      '    mode    => \'0644\',',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '    notify  => Exec[\'apply_sysctl_cassandra\'],',
      '  }',
      '',
      '  exec { \'apply_sysctl_cassandra\':',
      '    command     => \'/sbin/sysctl -p /etc/sysctl.d/99-cassandra.conf\',',
      '    path        => [\'/usr/bin\', \'/usr/sbin\', \'/bin\', \'/sbin\'],',
      '    refreshonly => true,',
      '  }',
      '',
      '  file { \'/etc/security/limits.d/cassandra.conf\':',
      '    ensure  => \'file\',',
      '    content => template(\'cassandra/cassandra_limits.conf.erb\'),',
      '    mode    => \'0644\',',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '  }',
      '}',
    ].join('\n'),
    'service.pp': [
      '# @summary Manages the Cassandra service, including password changes and range repair.',
      'class cassandra::service inherits cassandra {',
      '',
      '  # Cassandra service',
      '  service { \'cassandra\':',
      '    ensure     => running,',
      '    enable     => true,',
      '    hasstatus  => true,',
      '    hasrestart => true,',
      '  }',
      '',
      '  file { $cassandra::change_password_cql:',
      '    ensure  => file,',
      '    content => "ALTER USER cassandra WITH PASSWORD \'${cassandra::cassandra_password}\';\\\\n",',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '    mode    => \'0600\',',
      '  }',
      '',
      '  # Wait for Cassandra to start up before attempting to change password',
      '  exec { \'change_cassandra_password\':',
      '    command     => "cqlsh -u cassandra -p cassandra -f ${cassandra::change_password_cql}",',
      '    path        => $cassandra::cqlsh_path_env,',
      '    tries       => 12, # Try 12 times',
      '    try_sleep   => 10, # Wait 10 seconds between tries (total 2 minutes)',
      '    unless      => "cqlsh -u cassandra -p \'${cassandra::cassandra_password}\' -e \'SELECT cluster_name FROM system.local;\' ${cassandra::listen_address} >/dev/null 2>&1",',
      '    require     => Service[\'cassandra\'],',
      '  }',
      '',
      '  # Range Repair Service (Systemd)',
      '  $range_repair_ensure = $cassandra::enable_range_repair ? { true => \'running\', default => \'stopped\' }',
      '  $range_repair_enable = $cassandra::enable_range_repair ? { true => true, default => false }',
      '',
      '  file { \'/etc/systemd/system/range-repair.service\':',
      '    ensure  => \'file\',',
      '    content => template(\'cassandra/range-repair.service.erb\'),',
      '    owner   => \'root\',',
      '    group   => \'root\',',
      '    mode    => \'0644\',',
      '    notify  => Exec[\'systemctl_daemon_reload_range_repair\'],',
      '  }',
      '',
      '  exec { \'systemctl_daemon_reload_range_repair\':',
      '    command     => \'/bin/systemctl daemon-reload\',',
      '    path        => [\'/usr/bin\', \'/bin\'],',
      '    refreshonly => true,',
      '    before      => Service[\'range-repair\'],',
      '  }',
      '',
      '  service { \'range-repair\':',
      '    ensure    => $range_repair_ensure,',
      '    enable    => $range_repair_enable,',
      '    hasstatus => true,',
      '    hasrestart => true,',
      '    subscribe => File[\'/etc/systemd/system/range-repair.service\'],',
      '  }',
      '}',
    ].join('\n'),
    'java.pp': [
      '# @summary Manages Java installation for Cassandra.',
      'class cassandra::java inherits cassandra {',
      '',
      '  # Determine the correct Java package name based on the version and OS family',
      '  $java_package_name = $facts[\'os\'][\'family\'] ? {',
      '    \'RedHat\' => "java-${cassandra::java_version}-openjdk-headless",',
      '    \'Debian\' => "openjdk-${cassandra::java_version}-jre-headless",',
      '    default  => fail("Unsupported OS family for Java installation: ${facts[\'os\'][\'family\']}"),',
      '  }',
      '',
      '  $java_ensure_version = if $cassandra::java_package_version != \'\' {',
      '    $cassandra::java_package_version',
      '  } else {',
      '    \'present\'',
      '  }',
      '',
      '  package { $java_package_name:',
      '    ensure  => $java_ensure_version,',
      '  }',
      '}',
    ].join('\n'),
    'firewall.pp': [
      '# @summary Manages firewall rules for Cassandra.',
      'class cassandra::firewall {',
      '',
      '  # This class is now a placeholder. Firewall rules are no longer managed',
      '  # by this module to remove the dependency on puppetlabs/firewall.',
      '',
      '}',
    ].join('\n'),
  },
  templates: {
    'cassandra.yaml.erb': [
      '# cassandra.yaml',
      '# Generated by Puppet from cassandra/cassandra.yaml.erb. DO NOT EDIT.',
      '',
      'cluster_name: \'<%= @cassandra_version.start_with?("3.") ? @cluster_name : @cluster_name %>\'',
      'num_tokens: 256',
      'partitioner: org.apache.cassandra.dht.Murmur3Partitioner',
      '',
      'data_file_directories:',
      '    - \'<%= @data_dir %>\'',
      'commitlog_directory: \'<%= @commitlog_dir %>\'',
      'saved_caches_directory: /var/lib/cassandra/saved_caches',
      'hints_directory: \'<%= @hints_directory %>\'',
      '',
      'seed_provider:',
      '    - class_name: org.apache.cassandra.locator.SimpleSeedProvider',
      '      parameters:',
      '          - seeds: "<%= @seeds %>"',
      '',
      'listen_address: \'<%= @listen_address %>\'',
      'rpc_address: \'<%= @listen_address %>\'',
      'native_transport_port: 9042',
      'endpoint_snitch: GossipingPropertyFileSnitch',
      'dynamic_snitch: true',
      'authenticator: PasswordAuthenticator',
      'authorizer: CassandraAuthorizer',
      'start_native_transport: true',
      'role_manager: CassandraRoleManager',
      'cdc_raw_directory: /var/lib/cassandra/cdc_raw',
      'commit_failure_policy: stop',
      'commitlog_sync: periodic',
      'disk_failure_policy: stop',
      'incremental_backups: false',
      'max_hints_delivery_threads: 2',
      'native_transport_flush_in_batches_legacy: false',
      'native_transport_max_frame_size_in_mb: 128',
      'range_request_timeout_in_ms: 10000',
      'read_request_timeout_in_ms: 5000',
      'request_timeout_in_ms: 10000',
      'ssl_storage_port: 7001',
      'storage_port: 7000',
      'truncate_request_timeout_in_ms: 60000',
      'write_request_timeout_in_ms: 10000',
      'commitlog_sync_period_in_ms: 10000',
      '',
      '<% if @cassandra_version.start_with?(\'3.\') -%>',
      'start_rpc: true',
      'rpc_port: 9160',
      'rpc_keepalive: true',
      'thrift_framed_transport_size_in_mb: 15',
      '<% else -%>',
      '# Cassandra 4.x / 5.x specific settings',
      'enable_transient_replication: false',
      '<% end -%>',
      '',
      '<% if @ssl_enabled -%>',
      '# --- Internode (node-to-node) encryption ---',
      'server_encryption_options:',
      '  internode_encryption: <%= @internode_encryption || \'all\' %>  # \'none\' | \'dc\' | \'rack\' | \'all\'',
      '  keystore: <%= @keystore_path || "#{@target_dir}/etc/keystore.jks" %>',
      '  keystore_password: <%= @keystore_password %>',
      '  # Set to true only if you want nodes to present client certs (mutual TLS for internode)',
      '  require_client_auth: <%= @internode_require_client_auth ? \'true\' : \'false\' %>',
      '  <% if @truststore_path && @truststore_password -%>',
      '  truststore: <%= @truststore_path %>',
      '  truststore_password: <%= @truststore_password %>',
      '  <% end -%>',
      '  <% if @tls_protocol -%>',
      '  protocol: <%= @tls_protocol %>            # e.g., TLS',
      '  <% end -%>',
      '  <% if @tls_algorithm -%>',
      '  algorithm: <%= @tls_algorithm %>          # e.g., SunX509',
      '  <% end -%>',
      '  <% if @store_type -%>',
      '  store_type: <%= @store_type %>            # e.g., JKS',
      '  <% end -%>',
      '',
      '# --- Client (app-to-node) encryption ---',
      'client_encryption_options:',
      '  enabled: true',
      '  optional: <%= @client_optional ? \'true\' : \'false\' %>',
      '  keystore: <%= @client_keystore_path || "#{@target_dir}/etc/keystore.jks" %>',
      '  keystore_password: <%= @keystore_password %>',
      '<% end -%>',
    ].join('\n'),
    'cassandra-rackdc.properties.erb': [
      '# cassandra-rackdc.properties',
      '# Generated by Puppet from cassandra/cassandra-rackdc.properties.erb',
      '# Used by GossipingPropertyFileSnitch to determine rack and datacenter for this node.',
      '<% if @facts.key?(\'gce\') && @facts[\'gce\'][\'instance\'] && @facts[\'gce\'][\'instance\'][\'zone\'] -%>',
      '# GCE-specific snitch settings detected',
      'dc=<%= @facts[\'gce\'][\'instance\'][\'zone\'] %>',
      'rack=<%= @racks[@facts[\'gce\'][\'instance\'][\'zone\']] || \'rack1\' %>',
      '<% else -%>',
      '# Using default datacenter and rack from Hiera',
      'dc=<%= @datacenter %>',
      'rack=<%= @rack %>',
      '<% end -%>',
    ].join('\n'),
    'jvm-server.options.erb': [
      '# JVM configuration for Cassandra',
      '-ea',
      '',
      '-da:net.openhft...',
      '',
      '# Heap size',
      '-Xms<%= @max_heap_size %>',
      '-Xmx<%= @max_heap_size %>',
      '',
      '# GC type',
      '<% if @gc_type == \'G1GC\' %>',
      '-XX:+UseG1GC',
      '<% if @java_version.to_i < 14 %>',
      '-XX:G1HeapRegionSize=16M',
      '-XX:MaxGCPauseMillis=500',
      '-XX:InitiatingHeapOccupancyPercent=75',
      '-XX:+ParallelRefProcEnabled',
      '-XX:+AggressiveOpts',
      '<% end %>',
      '<% elsif @gc_type == \'CMS\' && @java_version.to_i < 14 %>',
      '-XX:+UseConcMarkSweepGC',
      '-XX:+CMSParallelRemarkEnabled',
      '-XX:SurvivorRatio=8',
      '-XX:MaxTenuringThreshold=1',
      '-XX:CMSInitiatingOccupancyFraction=75',
      '-XX:+UseCMSInitiatingOccupancyOnly',
      '-XX:+CMSClassUnloadingEnabled',
      '-XX:+AlwaysPreTouch',
      '<% end %>',
      '',
      '# GC logging',
      '<% if @java_version.to_i >= 11 %>',
      '-Xlog:gc*:/var/log/cassandra/gc.log:time,uptime,pid,tid,level,tags:filecount=10,filesize=100M',
      '<% else %>',
      '-Xloggc:/var/log/cassandra/gc.log',
      '-XX:+PrintGCDetails',
      '-XX:+PrintGCDateStamps',
      '-XX:+PrintHeapAtGC',
      '-XX:+PrintTenuringDistribution',
      '-XX:+PrintGCApplicationStoppedTime',
      '-XX:+UseGCLogFileRotation',
      '-XX:NumberOfGCLogFiles=10',
      '-XX:GCLogFileSize=100M',
      '<% end %>',
      '',
      '# Other common options',
      '-Dcassandra.jmx.local.port=7199',
      '-Djava.net.preferIPv4Stack=true',
      '-Dcom.sun.management.jmxremote.port=7199',
      '-Dcom.sun.management.jmxremote.rmi.port=7199',
      '-Dcom.sun.management.jmxremote.ssl=false',
      '-Dcom.sun.management.jmxremote.authenticate=false',
      '-Dlogback.configurationFile=logback.xml',
      '-Dlogback.defaultConfigurationFile=logback-default.xml',
      '',
      '<% if !@replace_address.empty? %>',
      '# Replace dead node at first boot (set by Hiera/Puppet)',
      '-Dcassandra.replace_address_first_boot=<%= @replace_address %>',
      '<% end %>',
    ].join('\n'),
    'cqlshrc.erb': [
      '# cqlshrc configuration file generated by Puppet',
      '',
      '[authentication]',
      'username = cassandra',
      'password = <%= @cassandra_password %>',
      '',
      '[connection]',
      'hostname = <%= @listen_address %>',
      'port = 9042',
      '',
      '<% if @ssl_enabled %>',
      '[ssl]',
      'certfile =  <%= "#{@target_dir}/etc/keystore.pem" %>',
      'version = SSLv23',
      'validate = false',
      '<% end %>',
    ].join('\n'),
    'range-repair.service.erb': [
      '[Unit]',
      'Description=Cassandra Range Repair Service',
      '',
      '[Service]',
      'Type=simple',
      'User=cassandra',
      'Group=cassandra',
      'ExecStart=/usr/local/bin/range-repair.sh',
      'Restart=on-failure',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
    ].join('\n'),
    'cassandra_limits.conf.erb': [
      '# Generated by Puppet',
      '# /etc/security/limits.d/cassandra.conf',
      '',
      '<% @limits_settings.each do |limit, value| -%>',
      '<%= @user %> - <%= limit %> <%= value %>',
      '<% end -%>',
    ].join('\n'),
    'sysctl.conf.epp': [
      '# Generated by Puppet',
      '# /etc/sysctl.d/99-cassandra.conf',
      '<% $settings.each |$key, $value| -%>',
      '<%= $key %> = <%= $value %>',
      '<% end -%>',
    ].join('\n'),
  },
  scripts: {
    'cassandra-upgrade-precheck.sh': '#!/bin/bash\n# Placeholder for cassandra-upgrade-precheck.sh\necho "Cassandra Upgrade Pre-check Script"',
    'cluster-health.sh': [
      '#!/bin/bash',
      '# cluster-health.sh: Provides a status overview of the Cassandra cluster.',
      '# Uses nodetool to check the state of all nodes.',
      '',
      'set -e',
      '',
      'echo "--- Cassandra Cluster Status ---"',
      'nodetool status',
      'echo "------------------------------"',
      'exit 0',
    ].join('\n'),
    'repair-node.sh': [
      '#!/bin/bash',
      '# repair-node.sh: Performs a primary-range repair on the local node.',
      '# This is a critical maintenance task for data consistency.',
      '',
      'set -e',
      '',
      'echo "--- Starting Node Repair (Primary Range) ---"',
      'nodetool repair -pr',
      'echo "--- Node Repair Finished ---"',
      'exit 0',
    ].join('\n'),
    'cleanup-node.sh': '#!/bin/bash\n# Placeholder for cleanup-node.sh\necho "Cleanup Node Script"',
    'take-snapshot.sh': '#!/bin/bash\n# Placeholder for take-snapshot.sh\necho "Take Snapshot Script"',
    'drain-node.sh': [
      '#!/bin/bash',
      '# drain-node.sh: Safely drains the node before shutdown or maintenance.',
      '# This flushes all memtables and stops listening for connections.',
      '',
      'set -e',
      '',
      'echo "--- Draining Cassandra Node ---"',
      'nodetool drain',
      'echo "--- Node Successfully Drained ---"',
      'exit 0',
    ].join('\n'),
    'rebuild-node.sh': '#!/bin/bash\n# Placeholder for rebuild-node.sh\necho "Rebuild Node Script"',
    'garbage-collect.sh': '#!/bin/bash\n# Placeholder for garbage-collect.sh\necho "Garbage Collect Script"',
    'assassinate-node.sh': '#!/bin/bash\n# Placeholder for assassinate-node.sh\necho "Assassinate Node Script"',
    'upgrade-sstables.sh': '#!/bin/bash\n# Placeholder for upgrade-sstables.sh\necho "Upgrade SSTables Script"',
    'backup-to-s3.sh': '#!/bin/bash\n# Placeholder for backup-to-s3.sh\necho "Backup to S3 Script"',
    'prepare-replacement.sh': '#!/bin/bash\n# Placeholder for prepare-replacement.sh\necho "Prepare Replacement Script"',
    'version-check.sh': '#!/bin/bash\n# Placeholder for version-check.sh\necho "Version Check Script"',
    'cassandra_range_repair.py': '#!/usr/bin/env python3\n# Placeholder for cassandra_range_repair.py\nprint("Cassandra Range Repair Python Script")',
    'range-repair.sh': '#!/bin/bash\n# Placeholder for range-repair.sh\necho "Range Repair Script"',
    'robust_backup.sh': '#!/bin/bash\necho "Robust Backup Script Placeholder"',
    'restore_from_backup.sh': '#!/bin/bash\necho "Restore from Backup Script Placeholder"',
    'node_health_check.sh': '#!/bin/bash\necho "Node Health Check Script Placeholder"',
    'rolling_restart.sh': '#!/bin/bash\necho "Rolling Restart Script Placeholder"',
  },
  files: {
    'jamm-0.3.2.jar': '', // Placeholder for binary file
  },
};
