
export const puppetCode = {
  root: {
    'metadata.json': [
      '{',
      '  "name": "ggonda-cassandra",',
      '  "version": "1.0.0",',
      '  "author": "ggonda",',
      '  "summary": "Production-ready Puppet profile to manage Apache Cassandra at scale.",',
      '  "license": "Apache-2.0",',
      '  "source": "https://github.com/ggonda/profile_ggonda_cassandra",',
      '  "project_page": "https://github.com/ggonda/profile_ggonda_cassandra",',
      '  "issues_url": "https://github.com/ggonda/profile_ggonda_cassandra/issues",',
      '  "dependencies": [',
      '    {',
      '      "name": "puppetlabs/stdlib",',
      '      "version_requirement": ">= 6.0.0 < 9.0.0"',
      '    },',
      '    {',
      '      "name": "puppetlabs/apt",',
      '      "version_requirement": ">= 7.0.0 < 9.0.0"',
      '    }',
      '  ],',
      '  "operatingsystem_support": [',
      '    {',
      '      "operatingsystem": "RedHat",',
      '      "operatingsystemrelease": [ "7", "8" ]',
      '    },',
      '    {',
      '      "operatingsystem": "CentOS",',
      '      "operatingsystemrelease": [ "7", "8" ]',
      '    },',
      '    {',
      '      "operatingsystem": "Debian",',
      '      "operatingsystemrelease": [ "9", "10", "11" ]',
      '    },',
      '    {',
      '      "operatingsystem": "Ubuntu",',
      '      "operatingsystemrelease": [ "18.04", "20.04", "22.04" ]',
      '    }',
      '  ],',
      '  "requirements": [',
      '    {',
      '      "name": "puppet",',
      '      "version_requirement": ">= 6.0.0 < 8.0.0"',
      '    }',
      '  ]',
      '}'
    ].join('\n'),
  },
  manifests: {
    'init.pp': [
      '# @summary Main entry point for the Cassandra profile.',
      '# @param version The version of Cassandra to install.',
      '# @param seeds An array of seed node IP addresses.',
      '# @param authenticator The authentication backend to use.',
      '# @param authorizer The authorization backend to use.',
      '# @param client_encryption_enabled Enable/disable client-to-node TLS.',
      '# @param server_encryption_enabled Enable/disable node-to-node TLS.',
      'class cassandra (',
      "  String \\$version                                  = '4.1.3',",
      "  String \\$package_name                              = 'cassandra',",
      "  String \\$service_name                              = 'cassandra',",
      "  Stdlib::Absolutepath \\$config_dir                   = '/etc/cassandra',",
      "  Optional[String] \\$java_package_name               = undef,",
      '',
      '  # cassandra.yaml - Basic Settings',
      "  String \\$cluster_name                              = 'MyCassandraCluster',",
      "  Array[Stdlib::IP::Address] \\$seeds                  = [\\$facts['networking']['ip']],",
      "  String \\$listen_address                            = \\$facts['networking']['ip'],",
      "  String \\$rpc_address                               = \\$facts['networking']['ip'],",
      "  Integer \\$num_tokens                               = 256,",
      "  String \\$endpoint_snitch                           = 'GossipingPropertyFileSnitch',",
      '',
      '  # cassandra.yaml - Directories',
      "  Array[Stdlib::Absolutepath] \\$data_file_directories = ['/var/lib/cassandra/data'],",
      "  Stdlib::Absolutepath \\$commitlog_directory           = '/var/lib/cassandra/commitlog',",
      "  Stdlib::Absolutepath \\$saved_caches_directory       = '/var/lib/cassandra/saved_caches',",
      '',
      '  # cassandra.yaml - Security Settings',
      "  String \\$authenticator                             = 'AllowAllAuthenticator',",
      "  String \\$authorizer                                = 'AllowAllAuthorizer',",
      '  Boolean \\$client_encryption_enabled                = false,',
      "  String \\$client_encryption_keystore                = 'conf/.keystore',",
      "  String \\$client_encryption_truststore              = 'conf/.truststore',",
      '  Boolean \\$server_encryption_enabled                = false,',
      "  String \\$server_encryption_keystore                = 'conf/.keystore',",
      "  String \\$server_encryption_truststore              = 'conf/.truststore',",
      '',
      '  # cassandra.yaml - Performance Tuning',
      "  Integer \\$concurrent_reads                         = 32,",
      "  Integer \\$concurrent_writes                        = 32,",
      "  Integer \\$concurrent_counter_writes                 = 32,",
      "  String \\$read_request_timeout_in_ms                = '5000',",
      "  String \\$write_request_timeout_in_ms               = '2000',",
      '',
      '  # cassandra-env.sh / jvm.options - JVM Settings',
      "  Optional[String] \\$jvm_max_heap_size                = undef, # e.g. '4G' or '8192M'",
      "  Optional[String] \\$jvm_new_heap_size                = undef, # e.g. '800M'",
      "  Optional[String] \\$jvm_extra_opts                   = undef, # e.g. '-Djava.rmi.server.hostname=<hostname>'",
      "  String \\$jvm_gc_type                               = 'G1GC',",
      '',
      ') {',
      '  contain cassandra::params',
      '  contain cassandra::java',
      '  contain cassandra::install',
      '  contain cassandra::config',
      '  contain cassandra::service',
      '',
      "  Class['cassandra::params']",
      "  -> Class['cassandra::java']",
      "  -> Class['cassandra::install']",
      "  -> Class['cassandra::config']",
      "  ~> Class['cassandra::service']",
      '}'
    ].join('\n'),
    'params.pp': [
      '# @summary Namespaces all parameters for the Cassandra profile.',
      'class cassandra::params {',
      '  \\$version                  = \\$cassandra::version',
      '  \\$package_name             = \\$cassandra::package_name',
      '  \\$service_name             = \\$cassandra::service_name',
      '  \\$config_dir               = \\$cassandra::config_dir',
      '  \\$java_package_name        = \\$cassandra::java_package_name',
      '',
      '  # Basic Settings',
      '  \\$cluster_name             = \\$cassandra::cluster_name',
      '  \\$seeds                    = \\$cassandra::seeds',
      '  \\$listen_address           = \\$cassandra::listen_address',
      '  \\$rpc_address              = \\$cassandra::rpc_address',
      '  \\$num_tokens               = \\$cassandra::num_tokens',
      '  \\$endpoint_snitch          = \\$cassandra::endpoint_snitch',
      '',
      '  # Directories',
      '  \\$data_file_directories    = \\$cassandra::data_file_directories',
      '  \\$commitlog_directory      = \\$cassandra::commitlog_directory',
      '  \\$saved_caches_directory   = \\$cassandra::saved_caches_directory',
      '',
      '  # Security Settings',
      '  \\$authenticator            = \\$cassandra::authenticator',
      '  \\$authorizer               = \\$cassandra::authorizer',
      '  \\$client_encryption_enabled = \\$cassandra::client_encryption_enabled',
      '  \\$client_encryption_keystore = \\$cassandra::client_encryption_keystore',
      '  \\$client_encryption_truststore = \\$cassandra::client_encryption_truststore',
      '  \\$server_encryption_enabled = \\$cassandra::server_encryption_enabled',
      '  \\$server_encryption_keystore = \\$cassandra::server_encryption_keystore',
      '  \\$server_encryption_truststore = \\$cassandra::server_encryption_truststore',
      '',
      '  # Performance Tuning',
      '  \\$concurrent_reads        = \\$cassandra::concurrent_reads',
      '  \\$concurrent_writes       = \\$cassandra::concurrent_writes',
      '  \\$concurrent_counter_writes = \\$cassandra::concurrent_counter_writes',
      '  \\$read_request_timeout_in_ms = \\$cassandra::read_request_timeout_in_ms',
      '  \\$write_request_timeout_in_ms = \\$cassandra::write_request_timeout_in_ms',
      '',
      '  # JVM Settings',
      '  \\$jvm_max_heap_size        = \\$cassandra::jvm_max_heap_size',
      '  \\$jvm_new_heap_size        = \\$cassandra::jvm_new_heap_size',
      '  \\$jvm_extra_opts           = \\$cassandra::jvm_extra_opts',
      '  \\$jvm_gc_type              = \\$cassandra::jvm_gc_type',
      '}'
    ].join('\n'),
    'java.pp': [
      '# @summary Installs Java, a dependency for Cassandra.',
      'class cassandra::java {',
      '  \\$java_package_name = \\$cassandra::params::java_package_name',
      '',
      '  # Determine the default Java package based on the OS family',
      "  \\$default_java_package = \\$facts['os']['family'] ? {",
      "    'RedHat' => 'java-1.8.0-openjdk-headless',",
      "    'Debian' => 'openjdk-8-jre-headless',",
      "    default  => fail(\\\"Unsupported OS family for Java installation: \\${facts['os']['family']}\\\"),",
      '  }',
      '',
      '  # Use the Hiera-provided package name if it exists, otherwise use the default',
      '  \\$package_to_install = pick(\\$java_package_name, \\$default_java_package)',
      '',
      "  package { 'java-for-cassandra':",
      '    ensure => installed,',
      '    name   => \\$package_to_install,',
      '  }',
      '}'
    ].join('\n'),
    'install.pp': [
      '# @summary Installs the Cassandra package.',
      'class cassandra::install {',
      '  \\$package_name = \\$cassandra::params::package_name',
      '  \\$version = \\$cassandra::params::version',
      '',
      "  \\$version_major_only = regsubst(\\$version, '^(\\\\d)\\\\.(\\\\d)\\\\..*', '\\\\1\\\\2')",
      '',
      "  case \\$facts['os']['family'] {",
      "    'RedHat': {",
      "      yumrepo { 'cassandra':",
      "        ensure   => 'present',",
      "        descr    => \\\"Apache Cassandra \\${version_major_only}x repo\\\",",
      "        baseurl  => \\\"https://downloads.apache.org/cassandra/redhat/\\${version_major_only}x/\\\",",
      '        enabled  => 1,',
      '        gpgcheck => 0, # For production, set to 1 and manage the key',
      '      }',
      "      Yumrepo['cassandra'] -> Package[\\$package_name]",
      '    }',
      "    'Debian': {",
      "      apt::source { 'cassandra':",
      "        location => 'https://downloads.apache.org/cassandra/debian',",
      "        release  => \\\"\\${version_major_only}x\\\",",
      "        repos    => 'main',",
      '        key      => {',
      "          id     => 'F758CE318D77295D',",
      "          source => 'https://downloads.apache.org/cassandra/KEYS',",
      '        },',
      '      }',
      "      Apt::Source['cassandra'] -> Package[\\$package_name]",
      '    }',
      '    default: {',
      '      fail("Cassandra installation is not supported on OS family \'\\${facts[\'os\'][\'family\']}\'")',
      '    }',
      '  }',
      '',
      '  package { \\$package_name:',
      '    ensure  => \\$version,',
      "    require => Class['cassandra::java'],",
      '  }',
      '}'
    ].join('\n'),
    'config.pp': [
      '# @summary Manages Cassandra configuration files.',
      'class cassandra::config {',
      '  \\$config_dir = \\$cassandra::params::config_dir',
      '  \\$config_file = "\\${config_dir}/cassandra.yaml"',
      '  \\$env_file = "\\${config_dir}/cassandra-env.sh"',
      '  \\$jvm_options_file = "\\${config_dir}/jvm-server.options"',
      "  \\$owner = 'cassandra'",
      "  \\$group = 'cassandra'",
      '',
      "  \\$seeds_string = join(\\$cassandra::params::seeds, ',')",
      '',
      '  file { \\$config_file:',
      '    ensure  => file,',
      '    owner   => \\$owner,',
      '    group   => \\$group,',
      "    mode    => '0640',",
      "    content => template('cassandra/cassandra.yaml.erb'),",
      '    require => Package[\\$cassandra::params::package_name],',
      '  }',
      '',
      '  file { \\$env_file:',
      '    ensure  => file,',
      '    owner   => \\$owner,',
      '    group   => \\$group,',
      "    mode    => '0640',",
      "    content => template('cassandra/cassandra-env.sh.erb'),",
      '    require => Package[\\$cassandra::params::package_name],',
      '  }',
      '',
      '  file { \\$jvm_options_file:',
      '    ensure  => file,',
      '    owner   => \\$owner,',
      '    group   => \\$group,',
      "    mode    => '0644',",
      "    content => template('cassandra/jvm-server.options.erb'),",
      '    require => Package[\\$cassandra::params::package_name],',
      '  }',
      '',
      '  # Ensure data directories exist with correct permissions',
      '  [ \\$cassandra::params::data_file_directories,',
      '    \\$cassandra::params::commitlog_directory,',
      '    \\$cassandra::params::saved_caches_directory,',
      '  ].flatten.each |Stdlib::Absolutepath \\$dir| {',
      '    file { \\$dir:',
      '      ensure  => directory,',
      '      owner   => \\$owner,',
      '      group   => \\$group,',
      "      mode    => '0750',",
      '      require => Package[\\$cassandra::params::package_name],',
      '    }',
      '  }',
      '}'
    ].join('\n'),
    'service.pp': [
      '# @summary Manages the Cassandra service.',
      'class cassandra::service {',
      '  \\$service_name = \\$cassandra::params::service_name',
      '',
      '  service { \\$service_name:',
      '    ensure    => running,',
      '    enable    => true,',
      '    hasstatus => true,',
      '  }',
      '}'
    ].join('\n'),
  },
  templates: {
    'cassandra.yaml.erb': [
      '# cassandra.yaml',
      '# Generated by Puppet from cassandra/cassandra.yaml.erb. DO NOT EDIT.',
      '',
      "cluster_name: '<%= @cassandra::params::cluster_name %>'",
      'num_tokens: <%= @cassandra::params::num_tokens %>',
      '',
      '# Seed provider',
      'seed_provider:',
      '  - class_name: org.apache.cassandra.locator.SimpleSeedProvider',
      '    parameters:',
      '      - seeds: "<%= @seeds_string %>"',
      '',
      'listen_address: <%= @cassandra::params::listen_address %>',
      'rpc_address: <%= @cassandra::params::rpc_address %>',
      '',
      'endpoint_snitch: <%= @cassandra::params::endpoint_snitch %>',
      '',
      '# Data directories',
      'data_file_directories:',
      '<% @cassandra::params::data_file_directories.each do |dir| -%>',
      '  - <%= dir %>',
      '<% end -%>',
      '',
      'commitlog_directory: <%= @cassandra::params::commitlog_directory %>',
      'saved_caches_directory: <%= @cassandra::params::saved_caches_directory %>',
      'commitlog_sync: periodic',
      'commitlog_sync_period_in_ms: 10000',
      '',
      '# Performance Tuning',
      'concurrent_reads: <%= @cassandra::params::concurrent_reads %>',
      'concurrent_writes: <%= @cassandra::params::concurrent_writes %>',
      'concurrent_counter_writes: <%= @cassandra::params::concurrent_counter_writes %>',
      '',
      '# Timeouts',
      'read_request_timeout_in_ms: <%= @cassandra::params::read_request_timeout_in_ms %>',
      'write_request_timeout_in_ms: <%= @cassandra::params::write_request_timeout_in_ms %>',
      '',
      '# Security',
      'authenticator: <%= @cassandra::params::authenticator %>',
      'authorizer: <%= @cassandra::params::authorizer %>',
      '',
      '# Client-to-Node Encryption',
      'client_encryption_options:',
      '  enabled: <%= @cassandra::params::client_encryption_enabled %>',
      '<% if @cassandra::params::client_encryption_enabled -%>',
      '  keystore: <%= @cassandra::params::client_encryption_keystore %>',
      '  keystore_password: "CHANGEME"',
      '  truststore: <%= @cassandra::params::client_encryption_truststore %>',
      '  truststore_password: "CHANGEME"',
      '<% end -%>',
      '',
      '# Node-to-Node Encryption',
      'server_encryption_options:',
      '  internode_encryption: <%= @cassandra::params::server_encryption_enabled ? "all" : "none" %>',
      '<% if @cassandra::params::server_encryption_enabled -%>',
      '  keystore: <%= @cassandra::params::server_encryption_keystore %>',
      '  keystore_password: "CHANGEME"',
      '  truststore: <%= @cassandra::params::server_encryption_truststore %>',
      '  truststore_password: "CHANGEME"',
      '<% end -%>'
    ].join('\n'),
    'cassandra-env.sh.erb': [
      '#!/bin/sh',
      '# This file is managed by Puppet from cassandra/cassandra-env.sh.erb.',
      '# Local changes will be overwritten.',
      '#',
      '',
      '# Set Java Heap Size',
      '<% if @cassandra::params::jvm_max_heap_size -%>',
      'MAX_HEAP_SIZE="<%= @cassandra::params::jvm_max_heap_size %>"',
      '<% end -%>',
      '<% if @cassandra::params::jvm_new_heap_size -%>',
      'HEAP_NEWSIZE="<%= @cassandra::params::jvm_new_heap_size %>"',
      '<% end -%>',
      '',
      '# Add extra JVM options',
      '<% if @cassandra::params::jvm_extra_opts -%>',
      'JVM_EXTRA_OPTS="$JVM_EXTRA_OPTS <%= @cassandra::params::jvm_extra_opts %>"',
      '<% end -%>',
      '',
      '# Use G1GC for modern garbage collection',
      '# This is a sensible default for most workloads on modern hardware',
      'if [ "$JVM_VENDOR" = "OpenJDK" ] && [ "$JVM_VERSION" -ge 7 ]; then',
      '  CASSANDRA_GC_OPTS="-XX:+UseG1GC -XX:G1RSetUpdatingPauseTimePercent=5 -XX:MaxGCPauseMillis=500"',
      'fi',
      'export CASSANDRA_GC_OPTS',
      ''
    ].join('\n'),
    'jvm-server.options.erb': [
      '# jvm-server.options',
      '# Generated by Puppet from cassandra/jvm-server.options.erb',
      '# This file is for Cassandra 4.x and later.',
      '',
      '# Basic memory settings',
      '<% if @cassandra::params::jvm_max_heap_size -%>',
      '-Xms<%= @cassandra::params::jvm_max_heap_size %>',
      '-Xmx<%= @cassandra::params::jvm_max_heap_size %>',
      '<% else -%>',
      '# Default if not set in Hiera',
      '-Xms4G',
      '-Xmx4G',
      '<% end -%>',
      '',
      '# GC Settings',
      '<% if @cassandra::params::jvm_gc_type == \'G1GC\' -%>',
      '-XX:+UseG1GC',
      '-XX:G1RSetUpdatingPauseTimePercent=5',
      '-XX:MaxGCPauseMillis=500',
      '<% else -%>',
      '-XX:+UseConcMarkSweepGC',
      '-XX:+CMSParallelRemarkEnabled',
      '<% end -%>',
      '',
      '# Other standard options',
      '-XX:+HeapDumpOnOutOfMemoryError',
      '-XX:HeapDumpPath=/var/lib/cassandra/java_pid<pid>.hprof',
      '-Dcassandra.jmx.local.port=7199',
      '-Dcom.sun.management.jmxremote.authenticate=false',
      '-Dcom.sun.management.jmxremote.ssl=false',
      ''
    ].join('\n'),
  },
  scripts: {
    'robust_backup.sh': [
      '#!/bin/bash',
      '# Robust backup script for a Cassandra node. Manages snapshots and optionally uploads to cloud storage.',
      'set -e',
      '',
      '# --- Configuration ---',
      'KEYSPACE="${1:-my_keyspace}" # Pass keyspace as first argument, or default',
      'BACKUP_BASE_DIR="/var/backups/cassandra"',
      'SNAPSHOT_NAME="snapshot_$(date +%Y-%m-%d_%H-%M-%S)"',
      'BACKUP_DIR="${BACKUP_BASE_DIR}/${KEYSPACE}/${SNAPSHOT_NAME}"',
      'DATADIR="/var/lib/cassandra/data"',
      '# Set to true to upload to a cloud bucket (e.g., S3, GCS)',
      'UPLOAD_TO_CLOUD=false',
      'CLOUD_BUCKET_PATH="s3://my-cassandra-backups/"',
      'LOG_FILE="/var/log/cassandra/backup.log"',
      '',
      '# --- Logging ---',
      'log() {',
      '  echo "$(date) - $1" | tee -a $LOG_FILE',
      '}',
      '',
      '# --- Main Logic ---',
      'log "Starting backup for keyspace: ${KEYSPACE}"',
      '',
      'log "Creating snapshot ${SNAPSHOT_NAME}..."',
      'nodetool snapshot -t "${SNAPSHOT_NAME}" "${KEYSPACE}"',
      'log "Snapshot created successfully."',
      '',
      'log "Copying snapshot files to ${BACKUP_DIR}..."',
      'mkdir -p "${BACKUP_DIR}"',
      'find "${DATADIR}/${KEYSPACE}" -type d -path "*/snapshots/${SNAPSHOT_NAME}" -exec rsync -a --no-o --no-g {}/ "${BACKUP_DIR}" \\;',
      'log "Snapshot files copied."',
      '',
      'if [ "$UPLOAD_TO_CLOUD" = true ]; then',
      '  log "Uploading backup to ${CLOUD_BUCKET_PATH}..."',
      '  # Add your cloud CLI command here, e.g.:',
      '  # aws s3 sync "${BACKUP_DIR}" "${CLOUD_BUCKET_PATH}${KEYSPACE}/${SNAPSHOT_NAME}/"',
      '  log "Cloud upload complete."',
      'fi',
      '',
      'log "Clearing snapshot ${SNAPSHOT_NAME}..."',
      'nodetool clearsnapshot -t "${SNAPSHOT_NAME}" "${KEYSPACE}"',
      'log "Snapshot cleared."',
      '',
      'log "Backup complete for keyspace: ${KEYSPACE}"',
      ''
    ].join('\n'),
    'restore_from_backup.sh': [
      '#!/bin/bash',
      '# Script to restore a Cassandra keyspace from a snapshot backup.',
      'set -e',
      '',
      '# --- Configuration ---',
      'KEYSPACE="${1:?Please provide a keyspace to restore.}"',
      'BACKUP_PATH="${2:?Please provide the full path to the backup directory.}"',
      'DATADIR="/var/lib/cassandra/data"',
      '',
      'echo "WARNING: This will stop Cassandra and replace data for keyspace ${KEYSPACE}."',
      'read -p "Are you sure you want to continue? (y/N) " -n 1 -r',
      'echo',
      'if [[ ! $REPLY =~ ^[Yy]$ ]]',
      'then',
      '    exit 1',
      'fi',
      '',
      'echo "Stopping Cassandra..."',
      'systemctl stop cassandra',
      '',
      'echo "Clearing old data for keyspace ${KEYSPACE}..."',
      'find "${DATADIR}/${KEYSPACE}" -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +',
      '',
      'echo "Restoring data from ${BACKUP_PATH}..."',
      '# Find the table directories in the backup',
      'for table_dir in "${BACKUP_PATH}"/*/; do',
      '  table_name=$(basename "$table_dir")',
      '  target_dir="${DATADIR}/${KEYSPACE}/${table_name}-*/"',
      '  if [ -d $target_dir ]; then',
      '    echo "  - Restoring ${table_name}"',
      '    rsync -a --no-o --no-g "${table_dir}" "${target_dir}"',
      '  else',
      '    echo "  - WARNING: Could not find target directory for table ${table_name}"',
      '  fi',
      'done',
      '',
      'echo "Fixing permissions..."',
      'chown -R cassandra:cassandra "${DATADIR}/${KEYSPACE}"',
      '',
      'echo "Starting Cassandra..."',
      'systemctl start cassandra',
      '',
      'echo "Waiting for node to come up..."',
      'sleep 30 # Adjust as needed',
      '',
      'echo "Running nodetool refresh for keyspace ${KEYSPACE}..."',
      'nodetool refresh "${KEYSPACE}"',
      '',
      'echo "Restore complete. Remember to run a full repair on the cluster."',
      ''
    ].join('\n'),
    'node_health_check.sh': [
      '#!/bin/bash',
      '# Performs a basic health check on the local Cassandra node.',
      '',
      'echo "--- Node Status ---"',
      'nodetool status',
      'echo',
      '',
      'echo "--- Gossip Info ---"',
      'nodetool gossipinfo',
      'echo',
      '',
      'echo "--- Ring Status ---"',
      'nodetool ring',
      'echo',
      '',
      'echo "--- Effective Ownership ---"',
      'nodetool describecluster',
      'echo',
      '',
      'echo "Health check complete. Review output for any issues (e.g., nodes in DN status)."',
      ''
    ].join('\n'),
    'rolling_restart.sh': [
      '#!/bin/bash',
      '# Performs a rolling restart of a Cassandra cluster.',
      '# This script should be run from one of the Cassandra nodes.',
      'set -e',
      '',
      '# --- Configuration ---',
      '# List of all node IPs in the cluster',
      'ALL_NODES=("10.0.1.10" "10.0.1.11" "10.0.1.12" "10.0.1.13")',
      'SSH_USER="admin"',
      'WAIT_TIME=60 # Seconds to wait between node restarts',
      '',
      'log() {',
      '  echo "[$(date)] - $1"',
      '}',
      '',
      'log "Starting rolling restart of the Cassandra cluster..."',
      '',
      'for node in "${ALL_NODES[@]}"; do',
      '  log "--- Processing node: ${node} ---"',
      '',
      '  log "Draining node ${node}..."',
      '  ssh "${SSH_USER}@${node}" "nodetool drain"',
      '  if [ $? -ne 0 ]; then',
      '    log "ERROR: Failed to drain node ${node}. Aborting restart."',
      '    exit 1',
      '  fi',
      '',
      '  log "Stopping Cassandra service on ${node}..."',
      '  ssh "${SSH_USER}@${node}" "sudo systemctl stop cassandra"',
      '',
      '  log "Starting Cassandra service on ${node}..."',
      '  ssh "${SSH_USER}@${node}" "sudo systemctl start cassandra"',
      '',
      '  log "Waiting for node ${node} to rejoin the cluster..."',
      '  # This is a simple check; a more robust check would loop until status is UN (Up/Normal)',
      '  sleep ${WAIT_TIME}',
      '  ssh "${SSH_USER}@${node}" "nodetool status"',
      '',
      '  log "Node ${node} has been restarted. Waiting ${WAIT_TIME} seconds before proceeding to the next node."',
      '  sleep ${WAIT_TIME}',
      'done',
      '',
      'log "Rolling restart completed for all nodes."',
      ''
    ].join('\n'),
  },
};

    