
export const cqlshrc = `
# cqlshrc configuration file generated by Puppet

[authentication]
username = cassandra
password = <%= @cassandra_password %>

[connection]
hostname = <%= @listen_address %>
port = 9042

<% if @ssl_enabled %>
[ssl]
certfile = <%= @target_dir %>/etc/keystore.pem
version = SSLv23
validate = false
<% end %>
`.trim();
