
export const rackdc_properties = `
# cassandra-rackdc.properties
# Generated by Puppet from cassandra_pfpt/cassandra-rackdc.properties.erb
dc=<%= @datacenter %>
rack=<%= @rack %>
<% @racks.each do |r, dc| -%>
<%= r %>=<%= dc %>:<%= r.split('-')[-1] %>
<% end -%>
`.trim();
